Update cygwin at 2013.5.31

diff --git a/bin/gtkdocize b/bin/gtkdocize
--- a/bin/gtkdocize
+++ b/bin/gtkdocize
@@ -4,21 +4,57 @@ progname=`echo "$0" | sed 's%^.*/%%'`
 
 PROGRAM=gtkdocize
 PACKAGE=gtk-doc
-VERSION=1.5
+VERSION=1.18
 
 prefix=/usr
-datarootdir=@datarootdir@
+datarootdir=/usr/share
 datadir=/usr/share
 
 # options
 docdir=.
 copy=no
+makefile=gtk-doc.make
+flavour=legacy
+
+# mini help
+usage="\
+usage: $progname [ --copy ] [ --docdir DIR ] [ --flavour {legacy|legacy-flat|no-tmpl|no-tmpl-flat} ]"
+
+# detect configure script
+no_configure_found=0
+if test -f configure.ac; then
+  configure=configure.ac
+elif test -f configure.in; then
+  configure=configure.in
+else
+  no_configure_found=1
+fi
+
+# check configure script for GTK_DOC_CHECK macro
+no_gtk_doc_check_found=0
+if test $no_configure_found -eq 0; then
+  macro=`grep '^GTK_DOC_CHECK' $configure 2>/dev/null`
+  if test $? -eq 0; then
+    # GTK_DOC_CHECK([1.14],[--flavour no-tmpl])
+    params=`echo $macro | sed -e 's/^GTK_DOC_CHECK(\ *\(.*\))/\1/'`
+    if echo $params | grep -q '^.*\,\ *\[\{0,1\}'; then
+      extra_options=`echo $params | sed -e 's/^.*\,\ *\[\{0,1\}\([^]]*\)\]\{0,1\}\ *$/\1/'`
+      #echo >&2 "DEBUG: adding extra options [$extra_options] to [$*]"
+      set - $* $GTKDOCIZE_FLAGS $extra_options
+    else
+      set - $* $GTKDOCIZE_FLAGS
+    fi
+  else
+    no_gtk_doc_check_found=1;
+  fi
+fi
 
 while test $# -gt 0; do
+  #echo >&2 "DEBUG: parsing args [$1]";
   case "$1" in
   --help)
-    echo "usage: $progname [ --copy ] [ --docdir DIR ]" 1>&2
-    exit 1 ;;
+    echo "$usage"
+    exit 0 ;;
   --version)
     echo "$PROGRAM ($PACKAGE) $VERSION"
     exit 0 ;;
@@ -29,29 +65,44 @@ while test $# -gt 0; do
     shift
     docdir="$1"
     shift ;;
+  --docdir=*)
+    docdir=`expr "X$1" : '[^=]*=\(.*\)'`
+    shift ;;
+  --flavour)
+    shift
+    flavour="$1"
+    shift ;;
+  --flavour=*)
+    flavour=`expr "X$1" : '[^=]*=\(.*\)'`
+    shift ;;
   -*)
     echo "$progname: unrecognised option '$1'" 1>&2
-    echo "usage: $progname [ --copy ] [ --docdir DIR ]" 1>&2
+    echo "$usage" 1>&2
     exit 1 ;;
   *)
     echo "$progname: too many arguments" 1>&2
-    echo "usage: $progname [ --copy ] [ --docdir DIR ]" 1>&2
+    echo "$usage" 1>&2
     exit 1 ;;
   esac
 done
 
-if test -f configure.ac; then
-  configure=configure.ac
-elif test -f configure.in; then
-  configure=configure.in
-else
+case "$flavour" in
+  legacy*)
+    ;;
+  no-tmpl*)
+    makefile=gtk-doc.notmpl.make
+    ;;
+  *)
+    echo "$progname: invalid value for --flavour" 1>&2
+    echo "$usage" 1>&2
+    exit 1 ;;
+esac
+
+if test $no_configure_found -eq 1; then
   echo "$progname: neither configure.ac nor configure.in exist" 1>&2
   exit 1
 fi
-
-if grep '^GTK_DOC_CHECK' $configure >/dev/null 2>&1; then
-  :
-else
+if test $no_gtk_doc_check_found -eq 1; then
   echo "$progname: GTK_DOC_CHECK not called in $configure" 1>&2
   exit 1
 fi
@@ -68,7 +119,7 @@ if test -n "$m4dir"; then
     cp -f $datadir/aclocal/gtk-doc.m4 $m4dir/ ||
       exit 1
   else
-    ln -sf $datadir/aclocal/gtk-doc.m4 $m4dir/ || 
+    ln -sf $datadir/aclocal/gtk-doc.m4 $m4dir/ ||
       cp -f $datadir/aclocal/gtk-doc.m4 $m4dir/ ||
       exit 1
   fi
@@ -76,10 +127,10 @@ fi
 
 rm -f $docdir/gtk-doc.make
 if test "$copy" = yes; then
-  cp -f $datadir/gtk-doc/data/gtk-doc.make $docdir/ ||
+  cp -f $datadir/gtk-doc/data/$makefile $docdir/gtk-doc.make ||
     exit 1
 else
-  ln -sf $datadir/gtk-doc/data/gtk-doc.make $docdir/ ||
-    cp -f $datadir/gtk-doc/data/gtk-doc.make $docdir/ ||
+  ln -sf $datadir/gtk-doc/data/$makefile $docdir/gtk-doc.make ||
+    cp -f $datadir/gtk-doc/data/$makefile $docdir/gtk-doc.make ||
     exit 1
 fi
diff --git a/bin/icu-config b/bin/icu-config
--- a/bin/icu-config
+++ b/bin/icu-config
@@ -20,10 +20,10 @@ prefix=
 loaddefs()
 {
 
-# Following from /usr/src/icu/icu-3.8-4/src/icu/source/config/mh-cygwin
+# Following from /usr/src/icu/icu-4.8.1-1/src/icu/source/config/mh-cygwin
 ## -*-makefile-*-
 #******************************************************************************
-#   Copyright (C) 1999-2007, International Business Machines
+#   Copyright (C) 1999-2010, International Business Machines
 #   Corporation and others.  All Rights Reserved.
 #******************************************************************************
 # This Makefile.inc is designed to be included into projects which make use
@@ -51,14 +51,15 @@ default_prefix="/usr"
 if [ "x${prefix}" = "x" ]; then prefix="$default_prefix"; fi
 exec_prefix="/usr"
 libdir="${exec_prefix}/lib"
-libexecdir="/usr/sbin"
+libexecdir="/usr/lib"
 bindir="/usr/bin"
+datarootdir="/usr/share"
 datadir="/usr/share"
 sbindir="/usr/sbin"
 
 # about the ICU version
-VERSION="3.8"
-UNICODE_VERSION="5.0"
+VERSION="4.8.1"
+UNICODE_VERSION="6.0"
 
 # The prefix for ICU libraries, normally 'icu'
 ICUPREFIX="icu"
@@ -133,11 +134,18 @@ ICULIBS_LAYOUTEX="-l${ICUPREFIX}lx${ICULIBSUFFIX}"
 ICULIBS_BASE="${LIBS} -L${libdir}"
 
 # for icu-config to test with
-ICULIBS_COMMON_LIB_NAME="${LIBICU}uc${ICULIBSUFFIX}${ICULIBSUFFIX_VERSION}.${SO}"
+ICULIBS_COMMON_LIB_NAME="${LIBICU}${COMMON_STUBNAME}${ICULIBSUFFIX}${ICULIBSUFFIX_VERSION}.${SO}"
+ICULIBS_COMMON_LIB_NAME_A="${LIBICU}${COMMON_STUBNAME}${ICULIBSUFFIX}.${A}"
 
 # ICULIBS is the set of libraries your application should link
 # with usually. Many applications will want to add ${ICULIBS_I18N} as well. 
 ICULIBS="${ICULIBS_BASE} ${ICULIBS_I18N} ${ICULIBS_COMMON} ${ICULIBS_DATA} "
+
+# Proper echo newline handling is needed in icu-config
+ECHO_N="-n"
+ECHO_C=""
+# Not currently being used but good to have for proper tab handling
+ECHO_T=""
 
 ##################################################################
 #
@@ -161,6 +169,10 @@ GENCMN="${sbindir}/gencmn"
 GENRB="${bindir}/genrb"
 PKGDATA="${bindir}/pkgdata"
 
+# moved here because of dependencies
+pkgdatadir="${datadir}/${PACKAGE}${ICULIBSUFFIX}/${VERSION}"
+pkglibdir="${libdir}/${PACKAGE}${ICULIBSUFFIX}/${VERSION}"
+
 ##################################################################
 #
 #       *3*  Information about the host
@@ -182,27 +194,28 @@ platform="U_CYGWIN"
 #       *4*  compiler flags and misc. options
 #
 ##################################################################
-AR="/usr/bin/ar"
+AR="ar"
 # initial tab keeps it out of the shell version.
 ARFLAGS=" ${ARFLAGS}"
-CC="gcc"
-CFLAGS="-O2 -pipe  ${THREADSCFLAGS} "
-CPP="gcc -E"
+CC="gcc-4"
+CFLAGS="-g -O2 -pipe  -Wall -ansi -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -Wno-long-long ${THREADSCFLAGS} "
+CPP="gcc-4 -E"
 CPPFLAGS="${THREADSCPPFLAGS} ${LIBCPPFLAGS} -I${prefix}/include"
-CXX="g++"
-CXXFLAGS="-O2 -pipe  ${THREADSCXXFLAGS} "
+CXX="g++-4"
+CXXFLAGS="-g -O2 -pipe  -W -Wall -ansi -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long ${THREADSCXXFLAGS} "
 DEFAULT_MODE="dll"
 DEFS="-DHAVE_CONFIG_H "
 FFLAGS="@FFLAGS@"
-INSTALL="/usr/bin/install -c"
+# use a consistent INSTALL 
+INSTALL="${SHELL} ${pkgdatadir}/install-sh -c"
 INSTALL_DATA="${INSTALL} -m 644"
 INSTALL_PROGRAM="${INSTALL}"
 INSTALL_SCRIPT="${INSTALL}"
-LDFLAGS="-Wl,--enable-auto-image-base ${RPATHLDFLAGS}"
+LDFLAGS="${RPATHLDFLAGS}"
 LIBS="-lpthread -lm  "
 LIB_M=""
-LIB_VERSION="38.0"
-LIB_VERSION_MAJOR="38"
+LIB_VERSION="48.1"
+LIB_VERSION_MAJOR="48"
 MKINSTALLDIRS="${SHELL} ${pkgdatadir}/mkinstalldirs"
 RANLIB="ranlib"
 RMV="rm -rf"
@@ -211,9 +224,9 @@ SHLIB_c="${CC} ${DEFS} ${CPPFLAGS} ${CFLAGS} ${LDFLAGS} -shared"
 SHLIB_cc="${CXX} ${DEFS} ${CPPFLAGS} ${CXXFLAGS} ${LDFLAGS} -shared"
 U_IS_BIG_ENDIAN="0"
 includedir="${prefix}/include"
-infodir="/usr/share/info"
+infodir="${datarootdir}/info"
 localstatedir="/var"
-mandir="/usr/share/man"
+mandir="${datarootdir}/man"
 oldincludedir="/usr/include"
 program_transform_name="s,x,x,"
 sharedstatedir="${prefix}/com"
@@ -226,12 +239,9 @@ INSTALL_L="${INSTALL_DATA}"
 #
 ##################################################################
 
-pkgdatadir="${datadir}/${PACKAGE}${ICULIBSUFFIX}/${VERSION}"
-pkglibdir="${libdir}/${PACKAGE}${ICULIBSUFFIX}/${VERSION}"
-
 # The basename of the ICU data file (i.e. icudt21b )
 ICUDATA_CHAR="l"
-ICUDATA_NAME="icudt38l"
+ICUDATA_NAME="icudt48l"
 
 # Defaults for pkgdata's mode and directories
 # The default data dir changes depending on what packaging mode 
@@ -267,10 +277,12 @@ GENCCODE_ASSEMBLY=""
 # The mh- file ("make fragment") for the platform is included here. 
 # It may override the above settings.
 # It is put last so that the mh-file can override anything.
+# The selfcheck is just a sanity check that this makefile is
+# parseable. The mh fragment is only included if this does not occur.
 
 ## -*-makefile-*-
 ## Cygwin-specific setup
-## Copyright (c) 2001-2006, International Business Machines Corporation and
+## Copyright (c) 2001-2010, International Business Machines Corporation and
 ## others. All Rights Reserved.
 
 ## Commands to generate dependency files
@@ -296,9 +308,15 @@ LIBCPPFLAGS=""
 LINK_c="${CXX} ${CXXFLAGS} ${LDFLAGS}"
 #LINK.cc=      ${CXX} ${CXXFLAGS} ${LDFLAGS}
 
+## Shared library options
+LD_SOOPTIONS="-Wl,-Bsymbolic"
+
 ## Commands to make a shared library
-SHLIB_c="${CC} ${CFLAGS} ${LDFLAGS} -shared"
-SHLIB_cc="${CXX} ${CXXFLAGS} ${LDFLAGS} -shared"
+# lines from the shell script (Make only)
+# the #SH# lines don't go through further postprocessing. 
+# so, they must be valid shell script starting from column 4
+SHLIB_c="${CC} ${CFLAGS} ${LDFLAGS} -shared "
+SHLIB_cc="${CXX} ${CXXFLAGS} ${LDFLAGS} -shared "
 
 ## Compiler switch to embed a runtime search path
 LD_RPATH=""
@@ -312,6 +330,8 @@ SO="dll"
 ## Non-shared intermediate object suffix
 STATIC_O="ao"
 LIBICU="cyg${ICUPREFIX}"
+## To have an import library is better on Cygwin
+IMPORT_LIB_EXT=".dll.a"
 
 ## Compilation rules
 
@@ -371,10 +391,11 @@ ICULIBS="${ICULIBS_BASE} ${ICULIBS_I18N} ${ICULIBS_COMMON} ${ICULIBS_DATA}"
 
 ## -*-sh-*-
 ## BEGIN of icu-config-bottom.
-## Copyright (c) 2002-2007, International Business Machines Corporation and
+## Copyright (c) 2002-2010, International Business Machines Corporation and
 ## others. All Rights Reserved.
 
-ICUUC_FILE=${bindir}/${ICULIBS_COMMON_LIB_NAME}
+ICUUC_FILE="${bindir}/${ICULIBS_COMMON_LIB_NAME}"
+ICUUC_FILE_A="${libdir}/${ICULIBS_COMMON_LIB_NAME_A}"
     
 #  echo ENABLE RPATH $ENABLE_RPATH and RPATHLDFLAGS=${RPATH_LDFLAGS}
 if [ "x$PKGDATA_MODE" = "x" ]; then
@@ -389,6 +410,7 @@ ME=`basename "$0"`
 
 allflags()
 {
+    echo "  --noverify             Don't verify that ICU is actually installed."
     echo "  --bindir               Print binary directory path (bin)"
     echo "  --cc                   Print C compiler used [CC]"
     echo "  --cflags               Print C compiler flags [CFLAGS]"
@@ -429,7 +451,10 @@ allflags()
     echo "  --sysconfdir           Print system config (etc) path"
     echo "  --unicode-version      Print version of Unicode data used in ICU ($UNICODE_VERSION)"
     echo "  --version              Print ICU version ($VERSION)"
-    echo "  --incfile              Print path to Makefile.inc (for -O option of pkgdata)"
+    echo "  --incfile              Print path to Makefile.inc"
+    echo "  --incpkgdatafile       Print path to pkgdata.inc (for -O option of pkgdata)"
+    echo "  --install              Print path to install-sh"
+    echo "  --mkinstalldirs        Print path to mkinstalldirs"
 }
 
 ## Print the normal usage message
@@ -460,11 +485,12 @@ usage()
 ## Check the sanity of current variables
 sanity()
 {
-    if [ ! -f ${ICUUC_FILE} ];
+    if [ ! -f "${ICUUC_FILE}" -a ! -f "${ICUUC_FILE_A}" ] && [ ${IGNORE_ICUUC_FILE_CHECK} = "no" ] && [ ${SANITY} = "sane" ];
     then
 	echo "### $ME: Can't find ${ICUUC_FILE} - ICU prefix is wrong."  1>&2
-	echo "###      Try the --prefix= or --exec-prefix= options " 1>&2
-	echo "###      or --detect-prefix"
+	echo "###      Try the --prefix= option " 1>&2
+	echo "###      or --detect-prefix" 1>&2
+        echo "###      (If you want to disable this check, use  the --noverify option)" 1>&2
 	echo "### $ME: Exitting." 1>&2
 	exit 2
     fi
@@ -477,11 +503,37 @@ if [ $# -lt 1 ]; then
     exit 1
 fi
 
+# For certain options (e.g. --detect-prefix) don't check for icuuc library file.
+
+IGNORE_ICUUC_FILE_CHECK="no";
+
+SANITY="sane"
+
+case "$1" in
+--noverify)
+    SANITY="nosanity"
+    shift
+    ;;
+esac
+
+case "$1" in 
+*prefix*)
+    IGNORE_ICUUC_FILE_CHECK="yes"
+    ;;
+esac
 
 # Load our variables from autoconf
 # ALWAYS load twice because of dependencies
 loaddefs
 loaddefs
+
+if [ $# -gt 0 -a $1 = "--selfcheck" ];
+then
+	echo "passed"
+	exit 
+	# EXIT for self check
+fi
+
 sanity
 
 while [ $# -gt 0 ];
@@ -492,13 +544,18 @@ do
     case "$arg" in
 
         # undocumented.
-	--debug)
+        --debug)
 	    set -x
 	    ;;
-
-        --so)
-            echo $SO
+        
+        --noverify)
+            echo "### $ME: Error: --noverify must be the first argument." 1>&2
+            exit 1
             ;;
+            
+    --so)
+        echo $SO
+        ;;
 
 	--bindir)
 	    echo $bindir
@@ -514,6 +571,14 @@ do
 
 	--sbindir)
 	    echo $sbindir
+	    ;;
+
+	--mkinstalldirs)
+	    echo ${MKINSTALLDIRS}
+	    ;;
+
+	--install)
+	    echo ${INSTALL}
 	    ;;
 
 	--invoke=*)
@@ -540,84 +605,83 @@ do
 	    ;;
 
 	--cflags)
-	    echo $CFLAGS
+	    echo $ECHO_N "${CFLAGS} ${ECHO_C}"
 	    ;;
 	    
 	--cc)
-	    echo $CC
+	    echo $ECHO_N "${CC} ${ECHO_C}"
 	    ;;
 	    
 	--cxx)
-	    echo $CXX
+	    echo $ECHO_N "${CXX} ${ECHO_C}"
 	    ;;
 
 	--cxxflags)
-	    echo $CXXFLAGS
+	    echo $ECHO_N "${CXXFLAGS} ${ECHO_C}"
 	    ;;
 
 	--cppflags)
 	    # Don't echo the -I. - it's unneeded.
-	    echo $CPPFLAGS | sed -e 's/-I. //'
+	    echo $ECHO_N "${CPPFLAGS} ${ECHO_C}" | sed -e 's/-I. //'
 	    ;;
 
 	--cppflags-searchpath)
-	    echo -I${prefix}/include
+	    echo $ECHO_N "-I${prefix}/include ${ECHO_C}"
 	    ;;
 
 	--cppflags-dynamic)
-	    echo $SHAREDLIBCPPFLAGS
+	    echo $ECHO_N "${SHAREDLIBCPPFLAGS} ${ECHO_C}"
 	    ;;
 
 	--cxxflags-dynamic)
-	    echo $SHAREDLIBCXXFLAGS
+	    echo $ECHO_N "${SHAREDLIBCXXFLAGS} ${ECHO_C}"
 	    ;;
 
 	--cflags-dynamic)
-	    echo $SHAREDLIBCFLAGS
+	    echo $ECHO_N "${SHAREDLIBCFLAGS} ${ECHO_C}"
 	    ;;
 
 	--ldflags-system)
-	    echo $LIBS
+	    echo $ECHO_N "${LIBS} ${ECHO_C}"
 	    ;;
 
 	--ldflags)
-	    echo $LDFLAGS $ICULIBS $LIBS 
+	    echo $ECHO_N "${LDFLAGS} ${ICULIBS} ${LIBS} ${ECHO_C}"
 # $RPATH_LDFLAGS
 	    ;;
 
 	--ldflags-libsonly)
-	    echo $ICULIBS_I18N $ICULIBS_COMMON $ICULIBS_DATA 
+	    echo $ECHO_N "${ICULIBS_I18N} ${ICULIBS_COMMON} ${ICULIBS_DATA} ${ECHO_C}"
 	    ;;
 
 	--ldflags-icuio)
-	    echo $ICULIBS_ICUIO
+	    echo $ECHO_N " ${ICULIBS_ICUIO} ${ECHO_C}"
 	    ;;
 
 	--ldflags-obsolete)
-	    echo $ICULIBS_OBSOLETE
+	    echo $ECHO_N "${ICULIBS_OBSOLETE} ${ECHO_C}"
 	    ;;
 
 	--ldflags-toolutil)
-	    echo $ICULIBS_TOOLUTIL
+	    echo $ECHO_N " ${ICULIBS_TOOLUTIL} ${ECHO_C}"
 	    ;;
 
 	--ldflags-layout)
-	    echo $ICULIBS_LAYOUT $ICULIBS_LAYOUTEX
+	    echo $ECHO_N "${ICULIBS_LAYOUT} ${ICULIBS_LAYOUTEX} ${ECHO_C}"
 	    ;;
 
 	--ldflags-searchpath)
-	    echo -L${libdir}
+	    echo $ECHO_N "-L${libdir} ${ECHO_C}"
 	    ;;
 
 	--detect-prefix)
 	    HERE=`echo $0 | sed -e "s/$ME//g"`
-	    if [ -f $HERE/../lib/${ICULIBS_COMMON_LIB_NAME} ]; then
-		prefix=$HERE/..
+	    if [ -f "${HERE}/../lib/${ICULIBS_COMMON_LIB_NAME}" -o -f  "${HERE}/../lib/${ICULIBS_COMMON_LIB_NAME_A}"  ]; then
+		prefix="${HERE}/.."
 		echo "## Using --prefix=${prefix}" 1>&2
 	    fi
 	    loaddefs
 	    loaddefs
-	    sanity
 	    ;;
 
 	--exec-prefix)
@@ -632,7 +696,6 @@ do
 	    prefix=$var
 	    loaddefs
 	    loaddefs
-	    sanity
 	    ;;
 
 	--sysconfdir)
@@ -644,44 +707,48 @@ do
 	    ;;
 
 	--shared-datadir)
-	    echo $datadir
+	    echo $ECHO_N "${datadir} ${ECHO_C}"
 	    ;;
 
         --incfile)
-	    echo $pkglibdir/Makefile.inc
+	    echo $ECHO_N "${pkglibdir}/Makefile.inc ${ECHO_C}"
+	    ;;
+
+	--incpkgdatafile)
+	    echo $ECHO_N "${pkglibdir}/pkgdata.inc ${ECHO_C}"
 	    ;;
 
 	--icudata)
-	    echo $ICUDATA_NAME
+	    echo $ECHO_N "${ICUDATA_NAME} ${ECHO_C}"
 	    ;;
 
 	--icudata-mode)
-	    echo $PKGDATA_MODE
+	    echo $ECHO_N "${PKGDATA_MODE} ${ECHO_C}"
 	    ;;
 
 	--icudata-install-dir)
-            echo $ICUPKGDATA_DIR
+        echo $ECHO_N "${ICUPKGDATA_DIR} ${ECHO_C}"
 	    ;;
 	    
 	--icudatadir)
-	    echo $ICUDATA_DIR
+	    echo $ECHO_N "${ICUDATA_DIR} ${ECHO_C}"
 	    ;;
 
 	--shlib-c)
-	    echo $SHLIB_c
+	    echo $ECHO_N "${SHLIB_c} ${ECHO_C}"
 	    ;;
 
 	--shlib-cc)
-	    echo $SHLIB_cc
+	    echo $ECHO_N "${SHLIB_cc} ${ECHO_C}"
 	    ;;
 
 	--version)
-            echo $VERSION
-            ;;
+        echo $ECHO_N $VERSION
+        ;;
 
-        --unicode-version)
-            echo $UNICODE_VERSION
-            ;;
+    --unicode-version)
+        echo $ECHO_N $UNICODE_VERSION
+        ;;
 
 	--help)
 	    usage
@@ -712,12 +779,18 @@ do
             ;;
     esac
     shift
+    
+    # Reset the ignore icuuc file check flag
+    if [ $IGNORE_ICUUC_FILE_CHECK = "yes" ]; then
+        IGNORE_ICUUC_FILE_CHECK="no"
+        sanity
+    fi
 done
-
+echo
 # Check once before we quit (will check last used prefix)
 sanity
 ## END of icu-config-bottom
 
 exit 0
 
-# Rebuilt on Thu Aug 28 17:45:16 GMT 2008
+# Rebuilt on Tue Jul 26 12:48:36 CEST 2011
diff --git a/bin/pdfroff b/bin/pdfroff
--- a/bin/pdfroff
+++ b/bin/pdfroff
@@ -3,24 +3,23 @@
 #
 # Function: Format PDF Output from groff Markup
 #
-# Copyright (C) 2005, Free Software Foundation, Inc.
+# Copyright (C) 2005, 2006, 2009, 2010, Free Software Foundation, Inc.
 # Written by Keith Marshall (keith.d.marshall@ntlworld.com)
 # 
 # This file is part of groff.
 # 
 # groff is free software; you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free
-# Software Foundation; either version 2, or (at your option) any later
-# version.
+# Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
 # 
 # groff is distributed in the hope that it will be useful, but WITHOUT ANY
 # WARRANTY; without even the implied warranty of MERCHANTABILITY or
 # FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 # 
-# You should have received a copy of the GNU General Public License along
-# with groff; see the file COPYING.  If not, write to the Free Software
-# Foundation, 51 Franklin St - Fifth Floor, Boston, MA 02110-1301, USA.
+# You should have received a copy of the GNU General Public License
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 # ------------------------------------------------------------------------------
 #
@@ -45,7 +44,7 @@
   #
   # Usage:  searchpath progname path
   #
-    IFS="${PATH_SEPARATOR-":"}" prog=':'
+    IFS=${PATH_SEPARATOR-":"} prog=':'
     for dir in $2
     do
       for ext in '' '.exe'
@@ -61,6 +60,12 @@
     done
     echo "$prog"
   }
+#
+# If the system maps '/bin/sh' to some 'zsh' implementation,
+# then we may need this hack, adapted from autoconf code.
+#
+  test x${ZSH_VERSION+"set"} = x"set" && NULLCMD=":" \
+    && (emulate sh) >$NULLDEV 2>&1 && emulate sh
 #
 # We need both 'grep' and 'sed' programs, to parse script options,
 # and we also need 'cat', to display help and some error messages,
@@ -119,9 +124,50 @@
     exit 1
   fi
 #
-# Set up temporary/intermediate file locations.
+# Identify the postprocessor command, for writing PDF output.
+# (May be forced, by defining PDFROFF_POSTPROCESSOR_COMMAND in the environment;
+#  if this is not set, leave blank to use the built in default).
 #
-  WRKFILE=${GROFF_TMPDIR=${TMPDIR-${TMP-${TEMP-"."}}}}/pdf$$.tmp
+  if test -n "${PDFROFF_POSTPROCESSOR_COMMAND}"
+  then
+    GROFF_GHOSTSCRIPT_INTERPRETER=`set command ${PDFROFF_POSTPROCESSOR_COMMAND};
+      echo $2`
+  fi
+#
+# Set up temporary/intermediate file locations, with traps to
+# clean them up on exit.  Note that, for greater portability, we
+# prefer to refer to events by number, rather than by symbolic
+# names; thus, the EXIT event is trapped as event zero.
+#
+  export TMPDIR GROFF_TMPDIR
+  TMPDIR=${GROFF_TMPDIR=${TMPDIR-${TMP-${TEMP-"."}}}}
+  if GROFF_TMPDIR=`exec 2>${NULLDEV}; mktemp -dt pdfroff-XXXXXXXXXX`
+  then
+  #
+  # We successfully created a private temporary directory,
+  # so to clean up, we may simply purge it.
+  #
+    trap "rm -rf ${GROFF_TMPDIR}" 0
+  #
+  else
+  #
+  # Creation of a private temporary directory was unsuccessful;
+  # fall back to user nominated directory, (using current directory
+  # as default), and schedule removal of only the temporary files.
+  #
+    GROFF_TMPDIR=${TMPDIR}
+    trap "rm -f ${GROFF_TMPDIR}/pdf$$.*" 0
+  fi
+  #
+  # In the case of abnormal termination events, we force an exit
+  # (with status code '1'), leaving the normal exit trap to clean
+  # up the temporary files, as above.  Note that we again prefer
+  # to refer to events by number, rather than by symbolic names;
+  # here we trap SIGHUP, SIGINT, SIGQUIT, SIGPIPE and SIGTERM.
+  #
+  trap "exit 1" 1 2 3 13 15
+#
+  WRKFILE=${GROFF_TMPDIR}/pdf$$.tmp
 #
   REFCOPY=${GROFF_TMPDIR}/pdf$$.cmp
   REFFILE=${GROFF_TMPDIR}/pdf$$.ref
@@ -129,11 +175,6 @@
   CS_DATA=""
   TC_DATA=${GROFF_TMPDIR}/pdf$$.tc
   BD_DATA=${GROFF_TMPDIR}/pdf$$.ps
-#
-# Set a trap, to delete temporary files on exit.
-# (FIXME: may want to include other signals, in released version).
-#
-  trap "rm -f ${GROFF_TMPDIR}/pdf$$.*" 0
 #
 # Initialise 'groff' format control settings,
 # to discriminate table of contents and document body formatting passes.
@@ -145,6 +186,7 @@
     help	reference-dictionary	no-reference-dictionary
     stylesheet	pdf-output		no-pdf-output
     version	report-progress		no-toc-relocation
+    emit-ps	keep-temporary-files	no-kill-null-pages
     "
 # Parse the command line, to identify 'pdfroff' specific options.
 # Collect all other parameters into new argument and file lists,
@@ -178,7 +220,7 @@
            case "$MATCH" in
 
              --help)
-               $CAT >&2 <<-ETX
+               $CAT <<-ETX
 		Usage: $CMD [-option ...] [--long-option ...] [file ...]
 
 		Options:
@@ -194,14 +236,22 @@
 		  	Enable console messages, indicating the progress of the
 		 	PDF document formatting process.
 
+		  --emit-ps
+		  	Emit PostScript output instead of PDF; this may be useful
+		 	when the ultimate PDF output is to be generated by a more
+		 	specialised postprocessor, (e.g. gpresent), rather than
+		 	the default GhostScript PDF writer.
+
 		  --pdf-output=name
-		  	Write the PDF output stream to file 'name'; if this option
-		 	is unspecified, standard output is used for PDF output.
+		  	Write the PDF, (or PostScript), output stream to file
+		 	'name'; if this option is unspecified, standard output
+		 	is used for PDF, (or PostScript), output.
 
 		  --no-pdf-output
-		 	Suppress the generation of PDF output entirely; use this
-		 	with the --reference-dictionary option, if processing a
-		 	document stream to produce only a reference dictionary.
+		 	Suppress the generation of PDF, (or PostScript), output
+		 	entirely; use this with the --reference-dictionary option,
+		 	if processing a document stream to produce only a
+		 	reference dictionary.
 
 		  --no-reference-dictionary
 		 	Suppress the generation of a '$CMD' reference dictionary
@@ -230,18 +280,35 @@
 		 	normally required to position the table of contents at the
 		 	start of a PDF document.
 
+		  --no-kill-null-pages
+		 	Suppress the 'null page' elimination filter, which is used
+		 	to remove the excess blank pages produced by the collation
+		 	algorithm used for 'toc-relocation'.
+
+		  --keep-temporary-files
+		 	Suppress the normal clean up of temporary files, which is
+		 	scheduled when 'pdfroff' completes.
+
 		ETX
                exit 0
                ;;
 
              --version)
 	       GROFF_STYLE="$GROFF_STYLE \"$1\""
-               SHOW_VERSION="GNU pdfroff (groff) version 1.19.2"
+               SHOW_VERSION="GNU pdfroff (groff) version 1.21"
                ;;
 
              --report-progress)
                SHOW_PROGRESS=echo
                ;;
+
+             --keep-temporary-files)
+               trap "" 0
+               ;;
+
+	     --emit-ps)
+	       PDFROFF_POSTPROCESSOR_COMMAND="$CAT"
+	       ;;
 
              --pdf-output)
 	       PDF_OUTPUT="$OPTARG"
@@ -265,6 +332,10 @@
 
 	     --no-toc-relocation)
 	       TC_DATA="" TOC_FORMAT="" BODY_FORMAT=""
+	       ;;
+
+	     --no-kill-null-pages)
+	       PDFROFF_COLLATE="$CAT" PDFROFF_KILL_NULL_PAGES=""
 	       ;;
 #
 #          any other non-null match must have matched more than one defined case,
@@ -296,7 +367,7 @@
 #
 #     Those standard options which expect an argument, but are specified with
 #     an intervening space, between flag and argument, must be reparsed, so we
-#     can trap illegal use of '-T dev', or missing input files.
+#     can trap invalid use of '-T dev', or missing input files.
 #
       -[dfFILmMnoPrTwW])
            OPTNAME="$1"
@@ -373,7 +444,7 @@
   then
     >> $REFFILE
     echo kickstart > $REFCOPY
-    test "${SHOW_PROGRESS+"set"}" = "set" && SAY=echo
+    test x${SHOW_PROGRESS+"set"} = x"set" && SAY=echo
 #
 #   In order to correctly resolve 'pdfmark' references,
 #   we need to have both the 'awk' and 'diff' programs available.
@@ -513,7 +584,7 @@
 # (Missing 'awk' or 'diff' may have disabled it, to avoid display
 #  of spurious messages associated with reference resolution).
 #
-  test "${SHOW_PROGRESS+"set"}" = "set" && SAY=echo
+  test x${SHOW_PROGRESS+"set"} = x"set" && SAY=echo
 #
 # If a document cover style sheet is specified ...
 # then we run a special formatting pass, to create a cover section file.
@@ -549,11 +620,24 @@
 # PostScript intermediate files into a single PDF output file.
 #
   $SAY >&2 $n "Writing PDF output ..$c"
-  PDFWRITE="$GS -dQUIET -dBATCH -dNOPAUSE -sDEVICE=pdfwrite"
+  if test -z "$PDFROFF_POSTPROCESSOR_COMMAND"
+  then
+    PDFROFF_POSTPROCESSOR_COMMAND="$GS -dQUIET -dBATCH -dNOPAUSE -dSAFER
+      -sDEVICE=pdfwrite -sOutputFile="${PDF_OUTPUT-"-"}
+
+  elif test -n "$PDF_OUTPUT"
+  then
+    exec > $PDF_OUTPUT
+  fi
 #
 # (This 'sed' script is a hack, to eliminate redundant blank pages).
 #
-  $SED '
+  ${PDFROFF_COLLATE-"$SED"} ${PDFROFF_KILL_NULL_PAGES-'
+      /%%Page:/{
+	N
+	/%%BeginPageSetup/b again
+      }
+      b
     :again
       /%%EndPageSetup/b finish
       /%%Page:/{
@@ -563,9 +647,9 @@
       b
     :finish
       N
-      /^%%Page:.*0 *Cg *EP/d
-    ' $TC_DATA $BD_DATA | $PDFWRITE -sOutputFile=${PDF_OUTPUT-"-"} $CS_DATA -
+      /^%%Page:.*\n0 Cg EP$/d
+    '} $TC_DATA $BD_DATA | $PDFROFF_POSTPROCESSOR_COMMAND $CS_DATA -
   $SAY >&2 ". done"
 #
 # ------------------------------------------------------------------------------
-# $RCSfile: pdfroff.sh,v $ $Revision: 1.7 $: end of file
+# $RCSfile: pdfroff.sh,v $ $Revision: 1.18 $: end of file
diff --git a/bin/updatedb b/bin/updatedb
--- a/bin/updatedb
+++ b/bin/updatedb
@@ -1,7 +1,7 @@
 #! /bin/sh
 # updatedb -- build a locate pathname database
-# Copyright (C) 1994, 1996, 1997, 2000, 2001, 2003, 2004, 2005, 2006
-# Free Software Foundation, Inc.
+# Copyright (C) 1994, 1996, 1997, 2000, 2001, 2003, 2004, 2005, 2006,
+# 2010, 2011 Free Software Foundation, Inc.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,8 +22,8 @@
 #set -x
 
 version='
-updatedb (GNU findutils) 4.4.0
-Copyright (C) 2007 Free Software Foundation, Inc.
+updatedb (GNU findutils) 4.5.11
+Copyright (C) 2007,2008,2009,2010 Free Software Foundation, Inc.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 This is free software: you are free to change and redistribute it.
 There is NO WARRANTY, to the extent permitted by law.
@@ -158,7 +158,15 @@ select_shell() {
 : ${NETPATHS=}
 
 # Directories to not put in the database, which would otherwise be.
-: ${PRUNEPATHS="/tmp /usr/tmp /var/tmp /afs /amd /sfs /proc"}
+: ${PRUNEPATHS="
+/afs
+/amd
+/proc
+/sfs
+/tmp
+/usr/tmp
+/var/tmp
+"}
 
 # Trailing slashes result in regex items that are never matched, which
 # is not what the user will expect.   Therefore we now reject such
@@ -194,7 +202,7 @@ export TMPDIR
 if test -n "$LIBEXECDIR" ; then
     : LIBEXECDIR already set, do nothing
 else
-    : ${LIBEXECDIR=/usr/sbin}
+    : ${LIBEXECDIR=/usr/lib}
 fi
 
 # The directory containing find.
@@ -210,6 +218,26 @@ fi
 : ${bigram:=${LIBEXECDIR}/bigram}
 : ${code:=${LIBEXECDIR}/code}
 
+make_tempdir () {
+    # This implementation is adapted from the GNU Autoconf manual.
+    {
+        tmp=`
+    (umask 077 && mktemp -d "$TMPDIR/updatedbXXXXXX") 2>/dev/null
+    ` &&
+        test -n "$tmp" && test -d "$tmp"
+    } || {
+	# This method is less secure than mktemp -d, but it's a fallback.
+	#
+	# We use $$ as well as $RANDOM since $RANDOM may not be available.
+	# We also add a time-dependent suffix.  This is actually somewhat
+	# predictable, but then so is $$.  POSIX does not require date to
+	# support +%N.
+	ts=`date +%N%S || date +%S 2>/dev/null`
+        tmp="$TMPDIR"/updatedb"$$"-"${RANDOM:-}${ts}"
+        (umask 077 && mkdir "$tmp")
+    }
+    echo "$tmp"
+}
 
 checkbinary () {
     if test -x "$1" ; then
@@ -226,9 +254,26 @@ do
 done
 
 
-PATH=/bin:/usr/bin:${BINDIR}; export PATH
-
-: ${PRUNEFS="nfs NFS proc afs proc smbfs autofs iso9660 ncpfs coda devpts ftpfs devfs mfs sysfs shfs user,remote system,remote"}
+: ${PRUNEFS="
+9P
+NFS
+afs
+autofs
+cifs
+coda
+devfs
+devpts
+ftpfs
+iso9660
+mfs
+ncpfs
+nfs
+nfs4
+proc
+shfs
+smbfs
+sysfs
+"}
 
 if test -n "$PRUNEFS"; then
 prunefs_exp=`echo $PRUNEFS |sed -e 's/\([^ ][^ ]*\)/-o -fstype \1/g' \
@@ -298,18 +343,16 @@ fi
 
 else # old
 
-if ! bigrams=`mktemp -t updatedbXXXXXXXXX`; then
-    echo mktemp failed >&2
-    exit 1
-fi
-
-if ! filelist=`mktemp -t updatedbXXXXXXXXX`; then
-    echo mktemp failed >&2
+if temp_directory="`make_tempdir`"; then
+    bigrams="${temp_directory}"/bigrams
+    filelist="${temp_directory}"/filelist
+else
+    echo "failed to create temporary directory" >&2
     exit 1
 fi
 
 rm -f $LOCATE_DB.n
-trap 'rm -f $bigrams $filelist $LOCATE_DB.n; exit' HUP TERM
+trap 'rm -f $LOCATE_DB.n; rm -rf "${temp_directory}"; exit' HUP TERM
 
 # Alphabetize subdirectories before file entries using tr.  James Woods says:
 # "to get everything in monotonic collating sequence, to avoid some
@@ -344,16 +387,16 @@ if test -n "$NETPATHS"; then
     exit $?
   fi
 fi
-} | tr / '\001' | $sort -f | tr '\001' / > $filelist
+} | tr / '\001' | $sort -f | tr '\001' / > "$filelist"
 
 # Compute the (at most 128) most common bigrams in the file list.
 $bigram $bigram_opts < $filelist | sort | uniq -c | sort -nr |
-  awk '{ if (NR <= 128) print $2 }' | tr -d '\012' > $bigrams
+  awk '{ if (NR <= 128) print $2 }' | tr -d '\012' > "$bigrams"
 
 # Code the file list.
-$code $bigrams < $filelist > $LOCATE_DB.n
+$code "$bigrams" < "$filelist" > $LOCATE_DB.n
 
-rm -f $bigrams $filelist
+rm -rf "${temp_directory}"
 
 # To reduce the chances of breaking locate while this script is running,
 # put the results in a temp file, then rename it atomically.
diff --git a/etc/profile b/etc/profile
--- a/etc/profile
+++ b/etc/profile
@@ -1,216 +1,195 @@
-# base-files version 3.7-1
+# To the extent possible under law, the author(s) have dedicated all 
+# copyright and related and neighboring rights to this software to the 
+# public domain worldwide. This software is distributed without any warranty. 
+# You should have received a copy of the CC0 Public Domain Dedication along 
+# with this software. 
+# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>. 
 
-# WARNING
-#
-# IF THIS FILE IS MODIFIED IT WILL NOT BE UPDATED BY THE CYGWIN
-# SETUP PROGRAM.  IT BECOMES YOUR RESPONSIBILITY.
+# base-files version 4.1-1
+
+# /etc/profile: executed by the command interpreter for login shells.
 
 # The latest version as installed by the Cygwin Setup program can
 # always be found at /etc/defaults/etc/profile
 
-# Some resources...
+# Modifying /etc/profile directly will prevent
+# setup from updating it.
 
+# System-wide profile file
+
+# Some resources...
 # Customizing Your Shell: http://www.dsl.org/cookbook/cookbook_5.html#SEC69
 # Consistent BackSpace and Delete Configuration:
 #   http://www.ibb.net/~anne/keyboard.html
 # The Linux Documentation Project: http://www.tldp.org/
 # The Linux Cookbook: http://www.tldp.org/LDP/linuxcookbook/html/
+# Greg's Wiki http://mywiki.wooledge.org/
 
-# Setup some default paths.  Note that this order will allow user installed
-#  software to override 'system' software
-
-# If you wish to change the path for all users, it is recommended you edit
-#  /etc/bash.bashrc
-
-# If you wish all future users to have some default setup, it is recommended you
-#  edit /etc/skel/.bashrc
-
-# If you wish to change the path on a user by user basis, it is recommended you
-#  edit ~/.bashrc
-
-PATH=/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:$PATH
-export PATH
-
-MANPATH=/usr/local/man:/usr/share/man:/usr/man:$MANPATH
-export MANPATH
-
-INFOPATH=/usr/local/info:/usr/share/info:/usr/info:$INFOPATH
-export INFOPATH
+# Setup some default paths. Note that this order will allow user installed
+# software to override 'system' software.
+# Modifying these default path settings can be done in different ways.
+# To learn more about startup files, refer to your shell's man page.
+PATH="/usr/local/bin:/usr/bin:${PATH}"
+MANPATH="/usr/local/man:/usr/share/man:/usr/man:${MANPATH}"
+INFOPATH="/usr/local/info:/usr/share/info:/usr/info:${INFOPATH}"
 
 # Set the user id
-USER="`id -un`"
-export USER
+USER="$(id -un)"
 
-# Here is how HOME is set, in order of priority, when starting from Windows
-#  1) From existing HOME in the Windows environment, translated to a Posix path
-#  2) from /etc/passwd, if there is an entry with a non empty directory field
-#  3) from HOMEDRIVE/HOMEPATH
-#  4) / (root)
+# TMP and TEMP as defined in the Windows environment must be kept
+# for windows apps, even if started from cygwin. However, leaving
+# them set to the default Windows temporary directory or unset
+# can have unexpected consequences for cygwin apps, so we define 
+# our own to match GNU/Linux behaviour.
+ORIGINAL_TMP=$TMP
+ORIGINAL_TEMP=$TEMP
+unset TMP TEMP
+tmp=$(cygpath -w "$ORIGINAL_TMP" 2> /dev/null)
+temp=$(cygpath -w "$ORIGINAL_TEMP" 2> /dev/null)
+TMP="/tmp"
+TEMP="/tmp"
 
-# If the home directory doesn't exist, create it.
-if [ ! -d "${HOME}" ]; then
-	mkdir -p "${HOME}"
-	echo "Copying skeleton files."
-	echo "These files are for the user to personalise"
-	echo "their cygwin experience."
-	echo
-	echo "These will never be overwritten."
-	echo
-	cd /etc/skel
-	/bin/find . -type f | while read f; do
-		fDest=`echo ${f} | sed -e 's/^\.//g'`
-		if [ ! -e "${HOME}${fDest}" -a ! -L "${HOME}${fDest}" ]; then
-			/usr/bin/install -D -p -v "${f}" "${HOME}/${fDest}"
-		fi
-	done
+# Define default printer
+p='/proc/registry/HKEY_CURRENT_USER/Software/Microsoft/Windows NT/CurrentVersion/Windows/Device'
+if [ -e "${p}" ] ; then
+  read -r PRINTER < "${p}" 
+  PRINTER=${PRINTER%%,*}
 fi
-
-chmod 1777 /tmp 2>/dev/null
-
-# Default to unix make mode
-MAKE_MODE=unix
-export MAKE_MODE
-
-# It is recommended that cvs uses ssh for it's remote shell environment
-CVS_RSH=/bin/ssh
-export CVS_RSH
-
-# Patches to Cygwin always appreciated ;)
-# CVSROOT=:pserver:anoncvs@sources.redhat.com:/cvs/src
-# export CVSROOT
-
-# Shell dependent settings
-case "`echo "_$0" | /usr/bin/tr '[:upper:]' '[:lower:]' | /usr/bin/sed -e 's/^_//'`" in
-bash     | -bash     | */bash | \
-bash.exe | -bash.exe | */bash.exe )
-	# Set a HOSTNAME variable
-	HOSTNAME=`hostname`
-	export HOSTNAME
-
-	# Set a default prompt of: user@host and current_directory
-	PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '
-	;;
-ksh*     | -ksh*     | */ksh* | \
-ksh*.exe | -ksh*.exe | */ksh*.exe )
-	# Set a HOSTNAME variable
-	typeset -l HOSTNAME
-
-	# Set a default prompt of: user@host and current_directory
-	PS1='^[]0;${PWD}^G
-^[[32m${USER}@${HOSTNAME} ^[[33m${PWD}^[[0m
-$ '
-	;;
-zsh*     | -zsh*     | */zsh* | \
-zsh*.exe | -zsh*.exe | */zsh*.exe )
-	# Set a default prompt of: user@host, a command counter, and current_directory
-	PS1='(%n@%m)[%h] %~ %% '
-	
-	# Set SHELL if not set
-	if [ ! -z "${ZSH_NAME}" -a -z "${SHELL}" ]; then
-		SHELL="/bin/zsh"
-		export SHELL	
-	fi
-	;;
-sh     | -sh     | */sh | \
-sh.exe | -sh.exe | */sh.exe )
-	# Set a simple prompt
-	PS1='$ '
-	;;
-* )
-	# Sorry, this shell has no defaults in /etc/profile,
-	#  feel free to add your own.
-
-	# If you have some recommendations for what these defaults
-	#  should be, please contact cygwin@cygwin.com with the
-	#  shell details and what you would like added.
-
-	# Thanks
-	
-	PS1='$ '
-	;;
-esac
-
-export PS1
-
-# Run all of the profile.d scripts
-# Note that these are supplied by separate packages
-# Ascending alphanumerical order enforced
-if [ -d "/etc/profile.d" ]; then
-	while read f; do
-		if [ -f "${f}" ]; then
-			. "${f}"
-		fi
-	done <<- EOF
-	`/bin/find -L /etc/profile.d -type f -iname '*.sh' -or -iname '*.zsh' | LC_ALL=C sort`
-	EOF
-fi
-
-# Uncomment to use the terminal colours set in DIR_COLOR
-# eval "`dircolors -b /etc/DIR_COLORS`"
+unset p
 
 # Default to removing the write permission for group and other
 #  (files normally created with mode 777 become 755; files created with
 #  mode 666 become 644)
 umask 022
 
-# Define default printer
-PRINTER=""
-case `uname -s` in
-CYGWIN_NT-*)
-	PRINTER="`regtool -q get '\user\Software\Microsoft\Windows NT\CurrentVersion\Windows\Device' | sed 's/,.*$//'`"
-	;;
-CYGWIN_9?-*)
-	PRINTER="`regtool -q get '\config\System\CurrentControlSet\Control\Print\Printers\Default'`"
-	;;
-esac
-export PRINTER
+# Here is how HOME is set, in order of priority, when starting from Windows
+#  1) From existing HOME in the Windows environment, translated to a Posix path
+#  2) from /etc/passwd, if there is an entry with a non empty directory field
+#  3) from HOMEDRIVE/HOMEPATH
+#  4) / (root)
+# If the home directory doesn't exist, create it.
+if [ ! -d "${HOME}" ]; then
+  if mkdir -p "${HOME}"; then
+    echo "Copying skeleton files."
+    echo "These files are for the users to personalise their cygwin experience."
+    echo
+    echo "They will never be overwritten nor automatically updated."
+    echo
+    cd /etc/skel || echo "WARNING: Failed attempt to cd into /etc/skel!"
+    /usr/bin/find . -type f | while read f; do
+      fDest=${f#.}
+      if [ ! -e "${HOME}${fDest}" -a ! -L "${HOME}${fDest}" ]; then
+        /usr/bin/install -D -p -v "${f}" "${HOME}/${fDest}"
+      fi
+    done
+    unset fDest
+  else
+    echo "${HOME} could not be created."
+    { [ -d "${TEMP}" ] && HOME="${TEMP}"; } ||
+    { [ -d "${TMP}" ] && HOME="${TMP}"; } ||
+    { [ -d /tmp ] && HOME=/tmp; } ||
+    HOME=/
+    echo "Setting HOME to ${HOME}."
+  fi
+fi
 
 # Make sure we start in home unless invoked by CHERE
 if [ ! -z "${CHERE_INVOKING}" ]; then
   unset CHERE_INVOKING
 else
-  cd "${HOME}"
+  cd "${HOME}" || echo "WARNING: Failed attempt to cd into ${HOME}!"
 fi
+
+# Shell dependent settings
+profile_d ()
+{
+  for file in $(export LC_COLLATE=C; echo /etc/profile.d/*.$1); do
+    [ -e "${file}" ] && . "${file}"
+  done
+  unset file
+}
+
+if [ ! "x${BASH_VERSION}" = "x"  ]; then
+  HOSTNAME="$(/usr/bin/hostname)"
+  profile_d sh
+  [ -f "/etc/bash.bashrc" ] && . "/etc/bash.bashrc"
+elif [ ! "x${KSH_VERSION}" = "x" ]; then
+  typeset -l HOSTNAME="$(/usr/bin/hostname)"
+  profile_d sh
+  PS1=$(print '\033]0;${PWD}\n\033[32m${USER}@${HOSTNAME} \033[33m${PWD/${HOME}/~}\033[0m\n$ ')
+elif [ ! "x${ZSH_VERSION}" = "x" ]; then
+  HOSTNAME="$(/usr/bin/hostname)"
+  profile_d zsh
+  PS1='(%n@%m)[%h] %~ %% '
+elif [ ! "x${POSH_VERSION}" = "x" ]; then
+  HOSTNAME="$(/usr/bin/hostname)"
+  PS1="$ "
+else 
+  HOSTNAME="$(/usr/bin/hostname)"
+  profile_d sh
+  PS1="$ "
+fi
+
+export PATH MANPATH INFOPATH USER TMP TEMP PRINTER HOSTNAME PS1 SHELL tmp temp
 
 # Check to see if mkpasswd/mkgroup needs to be run try and cut down the emails
 #   about this on the lists!
+#
+# The following are the conditions under which the group name special cases 
+#   will appear (where uid and gid are the effective user and group ids
+#   for the current user, and pgsid is the primary group associated with the
+#   SID for the current user):
+#       mkpasswd:
+#         gid is not in /etc/group
+#         uid is not in /etc/passwd
+#       passwd/group_GID_clash(<gid>/<pgsid>):
+#         gid is not in /etc/group
+#         uid is in /etc/passwd
+#         pgsid is in /etc/group (and does not match gid)
+#       mkgroup:
+#         gid is not in /etc/group
+#         uid is in /etc/passwd
+#         pgsid is not in /etc/group
+#
 # If this message keeps appearing and you are sure it's a mistake (ie, don't
 #   email about it!), comment out the test below.
-case `id -ng` in
+case "$(id -ng)" in
 mkpasswd )
-  echo "Your group is currently \"mkpasswd\".  This indicates that"
-  echo "the /etc/passwd (and possibly /etc/group) files should be rebuilt."
-  echo "See the man pages for mkpasswd and mkgroup then, for example, run"
-  echo "mkpasswd -l [-d] > /etc/passwd"
-  echo "mkgroup  -l [-d] > /etc/group"
-  echo "Note that the -d switch is necessary for domain users."
-  ;;
-
-mkgroup )
-  echo "Your group is currently \"mkgroup\".  This indicates that"
-  echo "the /etc/group (and possibly /etc/passwd) files should be rebuilt."
-  echo "See the man pages for mkpasswd and mkgroup then, for example, run"
-  echo "mkpasswd -l [-d] > /etc/passwd"
-  echo "mkgroup  -l [-d] > /etc/group"
-  echo "Note that the -d switch is necessary for domain users."
-  ;;
-
-mkgroup_l_d )
-  echo "Your group name is currently \"mkgroup_l_d\". This indicates that not"
-  echo "all domain users and groups are listed in the /etc/passwd and"
-  echo "/etc/group files."
-  echo "See the man pages for mkpasswd and mkgroup then, for example, run"
-  echo "mkpasswd -l -d > /etc/passwd"
-  echo "mkgroup  -l -d > /etc/group"
+  echo "Your group is currently \"mkpasswd\".  This indicates that your"
+  echo "gid is not in /etc/group and your uid is not in /etc/passwd."
   echo
-  echo "This message is only displayed once (unless you recreate /etc/group)"
-  echo "and can be safely ignored."
-
-  # only display the above once
-  cp -f /etc/group "${HOME}/group.mkgroup_l_d" \
-  && ( [ -w /etc/group ] || chmod --silent a+w /etc/group ; )\
-  && sed -e 's/^mkgroup_l_d/mkgroup-l-d/' "${HOME}/group.mkgroup_l_d" > /etc/group \
-  && chmod --silent --reference=/etc/passwd /etc/group
-  rm -f "${HOME}/group.mkgroup_l_d"
+  echo "The /etc/passwd (and possibly /etc/group) files should be rebuilt."
+  echo "See the man pages for mkpasswd and mkgroup then, for example, run"
+  echo
+  echo "mkpasswd -l [-d] > /etc/passwd"
+  echo "mkgroup  -l [-d] > /etc/group"
+  echo
+  echo "Note that the -d switch is necessary for domain users."
+  ;;
+passwd/group_GID_clash* )
+  echo "Your group is currently \"passwd/group_GID_clash(gid/pgsid)\".  This"
+  echo "indicates that your gid is not in /etc/group, but the pgsid (primary "
+  echo "group associated with your SID) is in /etc/group."
+  echo
+  echo "The /etc/passwd (and possibly /etc/group) files should be rebuilt."
+  echo "See the man pages for mkpasswd and mkgroup then, for example, run"
+  echo
+  echo "mkpasswd -l [-d] > /etc/passwd"
+  echo "mkgroup  -l [-d] > /etc/group"
+  echo
+  echo "Note that the -d switch is necessary for domain users."
+  ;;
+mkgroup )
+  echo "Your group is currently \"mkgroup\".  This indicates that neither"
+  echo "your gid nor your pgsid (primary group associated with your SID)"
+  echo "is in /etc/group."
+  echo
+  echo "The /etc/group (and possibly /etc/passwd) files should be rebuilt."
+  echo "See the man pages for mkpasswd and mkgroup then, for example, run"
+  echo
+  echo "mkpasswd -l [-d] > /etc/passwd"
+  echo "mkgroup  -l [-d] > /etc/group"
+  echo
+  echo "Note that the -d switch is necessary for domain users."
   ;;
 esac
diff --git a/usr/share/quilt/diff b/usr/share/quilt/diff
--- a/usr/share/quilt/diff
+++ b/usr/share/quilt/diff
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -80,7 +80,8 @@ included.
 }
 
 colorize() {
-	if [ -n "$opt_color" ]; then
+	if [ -n "$opt_color" ]
+	then
 		sed -e '
 		    s/^\(Index:\|---\|+++\|\*\*\*\) .*/'$color_diff_hdr'&'$color_clear'/
 		t ; s/^+.*/'$color_diff_add'&'$color_clear'/
@@ -109,15 +110,15 @@ do_diff()
 	then
 		[ -s "$old_file" ] || old_file=/dev/null
 		[ -s "$new_file" ] || new_file=/dev/null
-		if ! diff -q $old_file $new_file >/dev/null
+		if ! diff -q "$old_file" "$new_file" >/dev/null
 		then
 			export LANG=$ORIGINAL_LANG
-			$opt_diff $old_file $new_file
+			$opt_diff "$old_file" "$new_file"
 			export LANG=POSIX
 			true
 		fi
 	else
-		diff_file $file $old_file $new_file
+		diff_file "$file" "$old_file" "$new_file" | colorize
 	fi
 }
 
@@ -228,11 +229,18 @@ case "$opt_strip_level" in
 0 | 1 | ab)
 	;;
 *)
-	printf $"Cannot diff patches with -p%s, please specify -p0 or -p1 instead\n" \
+	printf $"Cannot diff patches with -p%s, please specify -p0, -p1, or -pab instead\n" \
 	       "$opt_strip_level" >&2
 	die 1
 	;;
 esac
+
+# If diffing against snapshot, ensure that snapshot is actually present
+if [ -n "$opt_snapshot" ] && [ ! -d "$QUILT_PC/$snap_subdir" ]
+then
+	printf $"No snapshot to diff against\n" >&2
+	die 1
+fi
 
 trap "die 1" SIGTERM
 
@@ -273,6 +281,10 @@ else
 	patches=( $last_patch )
 fi
 
+# Properly handle spaces in file names
+saved_IFS=$IFS
+IFS=$'\n'
+
 for patch in ${patches[@]}
 do
 	for file in $(files_in_patch_ordered $patch)
@@ -302,45 +314,16 @@ else
 	files=( $(sort -u $tmp_files) )
 fi
 
+IFS=$saved_IFS
+
 if [ -n "$opt_relative" ]
 then
-	patch_file=$(patch_file_name $last_patch)
-	patch_args=$(patch_args $last_patch)
 	workdir=$(gen_tempfile -d $PWD/quilt)
-
-	if [ ${#files[@]} -gt 0 ] \
-	   && ! ( cd $QUILT_PC/$last_patch &&
-		  cp -l --parents "${files[@]}" $workdir/ )
-	then
-		printf $"Failed to copy files to temporary directory\n" >&2
-		die 1
-	fi
-	# Now we may have some zero-size files that have no permissions
-	# (which represent files that the patch creates). Those may have
-	# been created in the meantime, but patch would refuse to touch
-	# them: We must remove them here.
-	find $workdir -type f -size 0 -exec rm -f '{}' ';'
-
-	if [ -s $patch_file ]
-	then
-		if ! cat_file $patch_file \
-		     | patch -d $workdir $QUILT_PATCH_OPTS $patch_args \
-		     	     --no-backup-if-mismatch -Ef \
-			     >/dev/null 2>/dev/null
-		then
-			# Generating a relative diff for a subset of files in
-			# the patch will fail. Also, if a patch was force
-			# applied, we know that it won't apply cleanly. In
-			# all other cases, print a warning.
-
-			if [ ! -e $QUILT_PC/$last_patch~refresh -a \
-			       ${#opt_files[@]} -eq 0 ]
-			then
-				printf $"Failed to patch temporary files\n" >&2
-			fi
-		fi
-	fi
+	apply_patch_temporarily "$workdir" "$last_patch" "${files[@]}" \
+	|| die 1
 fi
+
+setup_pager
 
 for file in "${files[@]}"
 do
@@ -351,27 +334,26 @@ do
 	then
 		old_file="$workdir/$file"
 	else
-		patch="$(first_modified_by $file ${patches[@]})"
+		patch=$(first_modified_by "$file" "${patches[@]}")
 		if [ -z "$patch" ]
 		then
 			[ -z "$opt_snapshot" ] \
 			&& printf $"File %s is not being modified\n" "$file" >&2
 			continue
 		fi
-		old_file="$(backup_file_name $patch $file)"
+		old_file=$(backup_file_name "$patch" "$file")
 	fi
 
-	next_patch=$(next_patch_for_file $last_patch $file)
+	next_patch=$(next_patch_for_file "$last_patch" "$file")
 	if [ -z "$next_patch" ]
 	then
 		new_file="$file"
 	else
-		new_file="$(backup_file_name $next_patch $file)"
+		new_file=$(backup_file_name "$next_patch" "$file")
 		files_were_shadowed=1
 	fi
 
-	do_diff "$file" "$old_file" "$new_file" \
-	| colorize
+	do_diff "$file" "$old_file" "$new_file"
 
 	if [ $? -ne 0 ]
 	then
diff --git a/usr/share/quilt/mail b/usr/share/quilt/mail
--- a/usr/share/quilt/mail
+++ b/usr/share/quilt/mail
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -21,18 +21,24 @@ fi
 
 usage()
 {
-	printf $"Usage: quilt mail {--mbox file|--send} [-m text] [--prefix prefix] [--sender ...] [--from ...] [--to ...] [--cc ...] [--bcc ...] [--subject ...]\n"
+	printf $"Usage: quilt mail {--mbox file|--send} [-m text] [-M file] [--prefix prefix] [--sender ...] [--from ...] [--to ...] [--cc ...] [--bcc ...] [--subject ...] [--reply-to message] [first_patch [last_patch]]\n"
 	if [ x$1 = x-h ]
 	then
 		printf $"
-Create mail messages from all patches in the series file, and either store
-them in a mailbox file, or send them immediately. The editor is opened
-with a template for the introduction. Please see %s for details.
+Create mail messages from a specified range of patches, or all patches in
+the series file, and either store them in a mailbox file, or send them
+immediately. The editor is opened with a template for the introduction.
+Please see %s for details.
+When specifying a range of patches, a first patch name of \`-' denotes the
+first, and a last patch name of \`-' denotes the last patch in the series.
 
 -m text
 	Text to use as the text in the introduction. When this option is
 	used, the editor will not be invoked, and the patches will be
 	processed immediately.
+
+-M file
+	Like the -m option, but read the introduction from file.
 
 --prefix prefix
 	Use an alternate prefix in the bracketed part of the subjects
@@ -55,7 +61,14 @@ with a template for the introduction. Please see %s for details.
 
 --to, --cc, --bcc
 	Append a recipient to the To, Cc, or Bcc header.
-" "/usr/share/doc/quilt-0.46/README.MAIL"
+
+--signature file
+	Append the specified signature to messages (defaults to ~/.signature
+	if found; use \`-' for no signature).
+
+--reply-to message
+	Add the appropriate headers to reply to the specified message.
+" "/usr/share/doc/quilt/README.MAIL"
 		exit 0
 	else
 		exit 1
@@ -65,7 +78,50 @@ with a template for the introduction. Please see %s for details.
 msgid()
 {
 	local timestamp=$(date --utc "+%Y%m%d%H%M%S.%N")
-	echo "$timestamp@${opt_sender#*@}"
+	echo "$timestamp@${opt_sender_address#*@}"
+}
+
+# See RFC 2822 Internet Message Format for how the In-Reply-To and
+# References headers are generated...
+
+in_reply_to_header() {
+	local message=$1 message_id
+
+	message_id=$(formail -x Message-ID: < "$message")
+	message_id=${message_id# }
+	[ -n "$message_id" ] && echo "In-Reply-To: $message_id"
+}
+
+references_header() {
+	local message=$1 message_id references in_reply_to
+
+	message_id=$(formail -x Message-ID: < "$message")
+	message_id=${message_id# }
+	
+	references=$(formail -x References: < "$message")
+	references=${references# }
+	if [ -z "$references" ]
+	then
+		in_reply_to=$(formail -x In-Reply-To: < "$message")
+		in_reply_to=${in_reply_to# }
+		if [ -n "$in_reply_to" ]
+		then
+			case "$in_reply_to" in
+			*@*@*)
+				;;
+			*)	references=$in_reply_to
+				;;
+			esac
+		fi
+	fi
+	if [ -z "$references" ]
+	then
+		references=$message_id
+	elif [ -n "$message_id" ]
+	then
+		references="$references"$'\n '"$message_id"
+	fi
+	[ -n "$references" ] && echo "References: $references"
 }
 
 process_mail()
@@ -73,28 +129,43 @@ process_mail()
 	local tmpfile=$(gen_tempfile)
 
 	cat > $tmpfile
+
 	set -- $($QUILT_DIR/scripts/edmail --charset $opt_charset \
 				  --extract-recipients To \
 				  --extract-recipients Cc \
 				  --extract-recipients Bcc \
 				  < $tmpfile)
-	if [ -n "$opt_send" ]; then
-		echo sendmail ${QUILT_SENDMAIL_ARGS--f "$opt_sender"} "$@"
+	if [ -n "$opt_send" ]
+	then
+		echo ${QUILT_SENDMAIL:-sendmail} \
+			${QUILT_SENDMAIL_ARGS--f "$opt_sender"} "$@"
 		$QUILT_DIR/scripts/edmail --charset $opt_charset \
-				 --remove-header Bcc "$@" < $tmpfile \
-		| sendmail ${QUILT_SENDMAIL_ARGS--f "$opt_sender"} "$@"
+				 --remove-header Bcc < $tmpfile \
+		| ${QUILT_SENDMAIL:-sendmail} \
+			${QUILT_SENDMAIL_ARGS--f "$opt_sender"} "$@"
 	else
-		local from_date=$(date "+%a %b %e %H:%M:%S %Y")
-		echo "From $opt_sender $from_date"
+		local from_date=$(LC_ALL=POSIX date "+%a %b %e %H:%M:%S %Y")
+		echo "From $opt_sender_address $from_date"
 		sed -e 's/^From />From /' $tmpfile
 		echo
 	fi
 	rm -f $tmpfile
 }
 
-options=`getopt -o m:h --long from:,to:,cc:,bcc:,subject: \
-		       --long send,mbox:,charset:,sender: \
-		       --long prefix: -- "$@"`
+join_lines() {
+	awk '
+		BEGIN { RS="\n\n" }
+		{ gsub(/[ \t\n]+/, " ")
+		  sub(/ $/, "")
+		  sub(/^ /, "")
+		  print }
+	'
+}
+
+options=`getopt -o m:M:h \
+		--long from:,to:,cc:,bcc:,subject: \
+		--long send,mbox:,charset:,sender: \
+		--long prefix:,reply-to:,signature: -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -104,11 +175,29 @@ fi
 eval set -- "$options"
 
 opt_prefix=patch
+if [ -r $HOME/.signature ]
+then
+	opt_signature="$(< $HOME/.signature)"
+fi
+
 while true
 do
 	case "$1" in
 	-m)
+		if [ -n "$opt_message" ]
+		then
+			echo "Introduction message already specified" >&2
+			exit 1
+		fi
 		opt_message=$2
+		shift 2 ;;
+	-M)
+		if [ -n "$opt_message" ]
+		then
+			echo "Introduction message already specified" >&2
+			exit 1
+		fi
+		opt_message=$(< "$2")
 		shift 2 ;;
 	--sender)
 		opt_sender=$2
@@ -140,6 +229,17 @@ do
 	--charset)
 		opt_charset=$2
 		shift 2 ;;
+	--reply-to)
+		opt_reply_to=$2
+		shift 2 ;;
+	--signature)
+		if [ "$2" = - ]
+		then
+			opt_signature=
+		else
+			opt_signature=$(< "$2")
+		fi
+		shift 2 ;;
 	-h)
 		usage -h ;;
 	--)
@@ -148,13 +248,49 @@ do
 	esac
 done
 
-if [ $# -gt 0 -o \( -z "$opt_send" -a -z "$opt_mbox" \) ]
+if [ $# -gt 2 -o \( -z "$opt_send" -a -z "$opt_mbox" \) ]
 then
 	usage
 fi
 
-if [ -z "$opt_sender" ]; then
-	hostname=$(hostname -f 2>/dev/null)
+# check if formail is installed before doing anything
+if ! type formail &> /dev/null
+then
+        echo "You have to install 'formail' to use 'quilt mail'" >&2
+        exit 1
+fi
+
+if [ $# -ge 1 ]
+then
+	if [ "$1" = - ]
+	then
+		first_patch="$(find_first_patch)" || exit 1
+	else
+		first_patch="$(find_patch "$1")" || exit 1
+	fi
+
+	if [ $# -ge 2 ]
+	then
+		if [ "$2" = - ]
+		then
+			last_patch="$(find_last_patch)" || exit 1
+		else
+			last_patch="$(find_patch "$2")" || exit 1
+		fi
+	else
+		last_patch=$first_patch
+	fi
+fi
+
+if [ -z "$opt_sender" ]
+then
+	if [ -e /etc/mailname ]
+	then
+		hostname=$(< /etc/mailname)
+	else
+		hostname=$(hostname -f 2>/dev/null)
+	fi
+
 	if [ "$hostname" = "${hostname/.}" ]
 	then
 		hostname=$(hostname)
@@ -169,8 +305,10 @@ Could not determine the envelope sender address. Please use --sender." >&2
 		;;
 	esac
 fi
+opt_sender_address=$(echo "$opt_sender" | sed -re 's:.*<([^<>]+)>.*:\1:')
 
-if [ -z "$opt_charset" ]; then
+if [ -z "$opt_charset" ]
+then
 	case "${LC_ALL:-$ORIGINAL_LANG}" in
 	*.UTF-8)
 		opt_charset=UTF-8
@@ -181,112 +319,118 @@ if [ -z "$opt_charset" ]; then
 	esac
 fi
 
-if [ "$(type -t quilt_mail_patch_filter 2> /dev/null)" != function ]; then
+if [ "$(type -t quilt_mail_patch_filter 2> /dev/null)" != function ]
+then
 	quilt_mail_patch_filter() {
-		local patch=$(cat)
-		local header=$(echo "$patch" | patch_header) body
+		local tmpdir=$(gen_tempfile -d)
+		cat > $tmpdir/patch
+		patch_header < $tmpdir/patch > $tmpdir/header
+		local subject
 		local -a mh
 
 		# Does this patch have a Subject: line?
-		local subject=$(echo $(echo "$header" \
-				| sed -n -e '/^$/q' \
-					 -e $'s/^Subject:[ \\t]//ip'))
+		subject=$(formail -x Subject: < $tmpdir/header)
 		if [ -n "$subject" ]
 		then
-			mh=( "Replace-Subject: $subject" )
-			body=$(echo "$patch" | awk '
-				in_body		{ print }
-				/^$/		{ in_body = 1 }
-				')
+			awk '
+			in_body		{ print }
+			/^$/		{ in_body = 1 }
+			' $tmpdir/patch > $tmpdir/body
 		fi
 
 		# Does this patch have DESC // subject // EDESC?
-		if [ ${#mh[@]} -eq 0 ]
+		if [ -z "$subject" ]
 		then
-			local desc=$(echo $(echo "$header" | awk '
-				/^EDESC\>/	{ desc = 0 }
+			local desc=$(awk '
+				/^EDESC/	{ desc = 0 }
 				desc		{ print }
-				/^DESC\>/	{ desc = 1 }
-				'))
+				/^DESC/	{ desc = 1 }
+				' $tmpdir/header)
 			if [ -n "$desc" ]
 			then
-				mh=( "Replace-Subject: $desc" )
-				body=$(echo "$patch" | awk '
-					/^DESC/		{ desc = 1 }
-					! desc		{ print }
-					/^EDESC/	{ desc = 0 }
-					')
+				subject=$(echo "$desc" | join_lines)
+				awk '
+				/^DESC/		{ desc = 1 }
+				! desc		{ print }
+				/^EDESC/	{ desc = 0 }
+				' $tmpdir/patch > $tmpdir/body
 			fi
 		fi
-
-		# Does the first paragraph look like a mail header?
-		#if [ ${#mh[@]} -eq 0 ]
-		#then
-		#	if echo "$header" | awk '
-		#		/^$/	{ exit (!mh || not_mh) }
-		#		END	{ exit (!mh || not_mh) }
-		#		{ if (tolower($0) ~ \
-		#		      /^(from|to|reply-to|date|cc):[ \t]/)
-		#		    mh = 1
-		#		  else
-		#		    not_mh = 1
-		#		}'
-		#	then
-		#		return 1
-		#	fi
-		#fi
 
 		# Is the first paragraph short enough to be used as the subject?
-		if [ ${#mh[@]} -eq 0 ]
+		if [ -z "$subject" ]
 		then
-			local para=$(echo $(echo "$header" \
-					    | sed -e $'/^[ \t]*$/q'))
+			local para=$(sed -e $'/^[ \t]*$/q' $tmpdir/header)
 			if [ ${#para} -gt 0 -a ${#para} -lt 150 ]
 			then
-				mh=( "Replace-Subject: $para" )
-				body="$(echo "$patch" | awk '
-					in_body		{ print }
-					/^[ \t]*$/	{ in_body = 1 }
-					')"
+				subject=$(echo "$para" | join_lines)
+				awk '
+				in_body		{ print }
+				/^[ \t]*$/	{ in_body = 1 }
+				' $tmpdir/patch > $tmpdir/body
 			fi
 		fi
 
-		#if ${#mh[@]} -eq 0 ]
-		#then
-		#	# Use the patch name as the subject.
-		#	mh=( "Replace-Subject: $1" )
-		#	body=$patch
-		#fi
-
-		if [ ${#mh[@]} -eq 0 ]
+		if [ -z "$subject" ]
 		then
+			rm -rf $tmpdir
 			return 1
 		fi
 
-		mh[0]=$(echo "${mh[0]}" \
-			| sed -e $'s/\\[[^]]*\\][ \t]*//gi' \
-			      -e $'s/\<\(fwd\|fw\|re\|aw\|tr\):[ \t]//gi')
+		subject=$(echo "$subject" \
+			  | sed -e $'s/^\\(\\(\\[[^]]*\\]\\|fwd:\\|fw:\\|re:\\|aw:\\|tr:\\)[ \t]*\\)*//i')
+		echo "Replace-Subject: $subject"
 
 		# Add recipients defined by some recognized keywords
-		local saved_IFS=$IFS; IFS=$'\n'
-		mh=( "${mh[@]}" 
-		     $(echo "$header" \
-		       | sed -n -e "/\<${LOGNAME:-$(whoami)}@/d" \
-				-e 's/^\(To\|Cc\):/Recipient-\1:/ip' \
-				-e 's/^\(Signed-off-by\|Acked-by\):/Recipient-Cc:/ip') )
-		IFS=$saved_IFS
 
-		printf "%s\n" "${mh[@]}"
+		# In Signed-off-by: and Acked-by: lines, try to recognize email
+		# addresses that contain commas and add quotes, e.g.,
+		#   Last, First <email>    =>    "Last, First" <email>
+
+		set -- Signed-off-by Acked-by Suggested-by Reviewed-by Requested-by Reported-by Tested-by Cc
+		set -- "$*"
+		set -- ${*// /\\|}
+
+		sed -n -e "/\<${LOGNAME:-$(whoami)}@/d" \
+		       -e 's/^\(\(To\|'"$*"'\):[ '$'\t'']*\)\([^"]*\(,[^"]*\)\+[^" '$'\t'']\)\([ '$'\t'']*<.*>\)/\1"\3"\5/I' \
+		       -e 's/^To:\(.*<.*@.*>\)/Recipient-To:\1/Ip' \
+		       -e 's/^\('"$*"'\):\(.*<.*@.*>\)/Recipient-Cc:\2/Ip' \
+		    $tmpdir/header
+
 		echo
-		echo "$body"
+		cat $tmpdir/body
+		rm -rf $tmpdir
 	}
 fi
 
-patches=( $(cat_series) )
+if [ -n "$first_patch" ]
+then
+	if [ -n "$last_patch" ]
+	then
+		set -- $(patches_before "$last_patch") "$last_patch"
+		while [ $# -ne 0 ]
+		do
+			[ "$1" = "$first_patch" ] && break
+			shift
+		done
+		if [ $# -eq 0 ]
+		then
+			printf $"Patch %s not applied before patch %s\n" \
+			       "$(print_patch $first_patch)" \
+			       "$(print_patch $last_patch)" >&2
+			exit 1
+		fi
+		patches=( "$@" )
+	else
+		patches=( "$first_patch" $(patches_after "$first_patch") )
+	fi
+else
+	patches=( $(cat_series) )
+fi
 total=${#patches[@]}
 
 tmpdir=$(gen_tempfile -d)
-trap "rm -rf $tmpdir" EXIT
+add_exit_handler "rm -rf $tmpdir"
 
 for patch in "${patches[@]}"
 do
@@ -295,9 +439,7 @@ do
 	| quilt_mail_patch_filter "$patch" > "$tmpdir/$patch"
 	status=${PIPESTATUS[1]}
 
-	subject=$(echo $(sed -n -e '/^$/q' \
-				-e $'s/^Replace-Subject:[ \t]*//ip' \
-			     "$tmpdir/$patch"))
+	subject=$(formail -x Replace-Subject: < "$tmpdir/$patch" | join_lines)
 	if [ $status -ne 0 -o -z "$subject" ]
 	then
 		printf \
@@ -323,22 +465,47 @@ dup_subjects=( $(
 		echo "$(print_patch "$patch")"
 	  done
 	) )
-if [ ${#dup_subjects[@]} -ne 0 ]; then
+if [ ${#dup_subjects[@]} -ne 0 ]
+then
 	printf $"Patches %s have duplicate subject headers.\n" \
 	       "$(set -- "${dup_subjects[*]/%/, }"; echo ${1%, })"
 	exit 1
+fi
+
+if [ -n "$opt_reply_to" ]
+then
+	if [ ! -e "$opt_reply_to" ]
+	then
+		printf $"File %s does not exist\n" "$opt_reply_to"
+		exit 1
+	fi
+
+	if [ -z "$opt_subject" ]
+	then
+		opt_subject="Re: $(formail -x Subject: < "$opt_reply_to" \
+			      | sed -e 's/^ *\([rR][eE]: *\)*//')"
+	fi
 fi
 
 introduction="$(gen_tempfile)"
 (
 	cat <<-EOF
 	Message-Id: <$(msgid)>
-	User-Agent: quilt/0.46-1
+	User-Agent: quilt/0.60-1
 	Date: $(date --rfc-822)
 	From: ${opt_from:-$opt_sender}
 	To: $(IFS=,; echo "${opt_to[*]}")
 	Cc: $(IFS=,; echo "${opt_cc[*]}")
 	Bcc: $(IFS=,; echo "${opt_bcc[*]}")
+	EOF
+
+	if [ -n "$opt_reply_to" ]
+	then
+		in_reply_to_header "$opt_reply_to"
+		references_header "$opt_reply_to"
+	fi
+
+	cat <<-EOF
 	Subject-Prefix: [$opt_prefix @num@/@total@]
 	Subject: $opt_subject
 
@@ -348,21 +515,24 @@ introduction="$(gen_tempfile)"
 		echo "$opt_message"
 		echo
 	fi
-	echo "-- "
-	[ -r $HOME/.signature ] && cat $HOME/.signature
+	if [ -n "$opt_signature" ]
+	then
+		echo "-- "
+		echo "$opt_signature"
+	fi
 ) | $QUILT_DIR/scripts/edmail --charset $opt_charset > $introduction
 
 if [ -z "$opt_message" ]
 then
-	if ! LANG=$ORIGINAL_LANG $EDITOR $introduction; then
+	if ! LANG=$ORIGINAL_LANG $EDITOR $introduction
+	then
 		rm -f $introduction
 		exit 1
 	fi
 fi
 
-if [ -z "$(sed -n -e '/^$/q' \
-		  -e $'s/^Subject:[ \t]*//ip' \
-	       $introduction)" ]
+subject=$(formail -x Subject: < $introduction | join_lines)
+if [ -z "$subject" ]
 then
 	if [ -z "$opt_message" ]
 	then
@@ -375,11 +545,12 @@ then
 	exit 1
 fi
 
-if [ -n "$opt_mbox" ]; then
+if [ -n "$opt_mbox" ]
+then
 	exec 1> $opt_mbox
 fi
 
-subject_prefix=$(sed -ne $'s/^Subject-Prefix:[ \t]*//p' $introduction)
+subject_prefix=$(formail -x Subject-Prefix: < $introduction | join_lines)
 [ -n "$subject_prefix" ] && subject_prefix="$subject_prefix "
 
 subject_prefix=${subject_prefix//\'/\'\'}
@@ -393,7 +564,8 @@ $introduction \
 		  --remove-empty-headers To Cc Bcc \
 | process_mail
 
-if [ -n "$opt_mbox" ]; then
+if [ -n "$opt_mbox" ]
+then
 	exec 1>> $opt_mbox
 fi
 
@@ -415,50 +587,70 @@ for patch in "${patches[@]}"; do
 	new_date="$(date --rfc-822 -d "1970/01/01 UTC $last_ts seconds")"
 
 	modify="$(awk '
-	sub(/^Recipient-/, "")	{ r = $0
-				  sub(/:.*/, "", r)
-				  s = $0
-				  sub(/^[^:]*:[ \t]*/, "", s)
-				  gsub(/'\''/, "'\'\''", s)
-				  print "--add-recipient " r "='\''" s "'\''"
-				}
-	sub(/^Replace-/, "")	{ r = $0
-				  sub(/:.*/, "", r)
-				  s = $0
-				  sub(/^[^:]*:[ \t]*/, "", s)
-				  gsub(/'\''/, "'\'\''", s)
-				  print "--replace-header " r "='\''" s "'\''"
-				}
+	in_header	{ if (/^[ \t]/) {
+			    headers[n] = headers[n] "\n" $0
+			    next }
+			  in_header = 0 }
+	sub(/^Recipient-/, "")	{ headers[++n] = $0
+				  options[n] = "--add-good-recipient"
+				  in_header = 1
+				  next }
+	sub(/^Replace-/, "")	{ headers[++n] = $0
+				  options[n] = "--replace-header"
+				  in_header = 1
+				  next }
+	END			{ for(n = 1; n in headers; n++) {
+				    r = headers[n]
+				    sub(/:.*/, "", r)
+				    s = headers[n]
+				    sub(/^[^:]*:[ \t]*/, "", s)
+				    gsub(/'\''/, "'\'\''", s)
+				    print options[n] " " r "='\''" s "'\'' \\" } }
 	' $body)"
+#	echo "$modify" | sed -e 's/^/>> /' >&2
 	p=${subject_prefix//@num@/$(printf %0*d ${#total} $num)}
 	p=${p//@total@/$total}
-	(	echo "Message-Id: <$(msgid)>"
-		sed -n -e '/^$/q' \
-		    -e 's/^Message-Id:/References:/' \
-		    -e p \
-		    $introduction
-		echo "Content-Disposition: inline; filename=$patch"
-		sed -n -e '/^$/q' \
-		    -e '/^Recipient-.*:/d' \
-		    -e '/^Replace-.*:/d' \
-		    -e p \
-		    $body
+
+	# Make pipes fail if any of their commands fail (requires bash 3):
+	set -o pipefail
+
+	( (	echo "Message-Id: <$(msgid)>"
 		awk '
-		/^$/	{ in_body = 1 }
-		in_body	{ print }
-		' $body
-		echo -e '\n-- '
-		[ -r $HOME/.signature ] && cat $HOME/.signature
+		    /^$/	{ exit }
+		    tolower($0) !~ /^(message-id|references|in-reply-to):/ \
+		    		{ print }
+		' $introduction
+		references_header $introduction
+		echo "Content-Disposition: inline; filename=$patch"
+		awk '
+		    kill_header { if (/^[ \t]/) next ; kill_header = 0 }
+		    !in_body && tolower($0) ~ /^(recipient|replace)-.*:/ \
+				{ kill_header = 1 ; next }
+		    /^$/	{ in_body = 1 }
+				{ print }
+		    ' $body
+		echo
+		#if [ -n "$opt_signature" ]
+		#then
+		#	echo '-- '
+		#	echo "$opt_signature"
+		#fi
 	) | eval $QUILT_DIR/scripts/edmail --charset $opt_charset \
 		--replace-header Date="\"$new_date\"" \
 		To Cc Bcc \
-		$modify \
+		"$modify" \
 	| sed -e $'s/^\\(Subject:[ \t]\\)/\\1'"$p"'/' \
 	      -e '/^Subject-Prefix:/d' \
 	| $QUILT_DIR/scripts/edmail --remove-empty-headers \
-	| process_mail
+	| process_mail ) 2> $tmpdir/err
 
-	if [ ${PIPESTATUS[1]} -ne 0 ]; then
+	status=$?
+	if [ -s $tmpdir/err ]
+	then
+		sed -e "s/^/${patch//\//\\/}: /" <  $tmpdir/err >&2
+	fi
+	if [ $status -ne 0 ]
+	then
 		printf $"Introduction saved as %s\n" "$introduction" >&2
 		exit 1
 	fi
@@ -467,7 +659,8 @@ for patch in "${patches[@]}"; do
 	# sequences.
 
 	#content_length=${#body}
-	#if [ -n "$(echo "$body" | tr -d '\0-\177')" ]; then
+	#if [ -n "$(echo "$body" | tr -d '\0-\177')" ]
+	#then
 	#	charset=UTF-8
 	#fi
 	# Content-Transfer-Encoding: 7bit
diff --git a/usr/share/quilt/new b/usr/share/quilt/new
--- a/usr/share/quilt/new
+++ b/usr/share/quilt/new
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -19,12 +19,19 @@ fi
 
 usage()
 {
-	printf $"Usage: quilt new {patchname}\n"
+	printf $"Usage: quilt new [-p n|-p ab] {patchname}\n"
 	if [ x$1 = x-h ]
 	then
 		printf $"
 Create a new patch with the specified file name, and insert it after the
-topmost patch in the patch series file.
+topmost patch. The name can be prefixed with a sub-directory name, allowing
+for grouping related patches together.
+
+-p n	Create a -p n style patch (-p0 or -p1 are supported).
+
+-p ab	Create a -p1 style patch, but use a/file and b/file as the
+	original and new filenames instead of the default
+	dir.orig/file and dir/file names.
 
 Quilt can be used in sub-directories of a source tree. It determines the
 root of a source tree by searching for a %s directory above the
@@ -38,7 +45,7 @@ in the directory tree.
 	fi
 }
 
-options=`getopt -o h -- "$@"`
+options=`getopt -o p:h -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -50,6 +57,8 @@ eval set -- "$options"
 while true
 do
 	case "$1" in
+	-p)	opt_strip_level=$2
+		shift 2 ;;
 	-h)
 		usage -h ;;
 	--)
@@ -58,9 +67,27 @@ do
 	esac
 done
 
+case "$opt_strip_level" in
+'' | 1)
+	opt_strip_level= ;;
+0 | ab)
+	;;
+*)
+	printf $"Cannot create patches with -p%s, please specify -p0, p1, or -pab instead\n" \
+	       "$opt_strip_level" >&2
+	exit 1
+	;;
+esac
+
 if [ $# -ne 1 ]
 then
 	usage
+fi
+
+if [ "$QUILT_PATCHES" = "$QUILT_PC" ]
+then
+	printf $"QUILT_PATCHES(%s) must differ from QUILT_PC(%s)\n" "$QUILT_PATCHES" "$QUILT_PC"
+	exit 1
 fi
 
 patch=${1#$QUILT_PATCHES/}
@@ -75,7 +102,7 @@ create_db
 rm -rf "$QUILT_PC/$patch"
 mkdir -p "$QUILT_PC/$patch"
 
-if ! insert_in_series $patch || \
+if ! insert_in_series $patch ${opt_strip_level:+-p$opt_strip_level} || \
    ! add_to_db $patch
 then
 	printf $"Failed to create patch %s\n" "$(print_patch $patch)" >&2
diff --git a/usr/share/quilt/refresh b/usr/share/quilt/refresh
--- a/usr/share/quilt/refresh
+++ b/usr/share/quilt/refresh
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -19,7 +19,7 @@ fi
 
 usage()
 {
-	printf $"Usage: quilt refresh [-p n|-p ab] [-u|-U num|-c|-C num] [-f] [--no-timestamps] [--no-index] [--diffstat] [--sort] [--backup] [--strip-trailing-whitespace] [patch]\n"
+	printf $"Usage: quilt refresh [-p n|-p ab] [-u|-U num|-c|-C num] [-z[new_name]] [-f] [--no-timestamps] [--no-index] [--diffstat] [--sort] [--backup] [--strip-trailing-whitespace] [patch]\n"
 
 	if [ x$1 = x-h ]
 	then
@@ -46,6 +46,11 @@ patch.
 	Create a unified diff (-u, -U) with num lines of context. Create
 	a context diff (-c, -C) with num lines of context. The number of
 	context lines defaults to 3.
+
+-z[new_name]
+	Create a new patch containing the changes instead of refreshing the
+	topmost patch. If no new name is specified, \`-2' is added to the
+	original patch name, etc. (See the fork command.)
 
 --no-timestamps
 	Do not include file timestamps in patch headers.
@@ -77,14 +82,14 @@ die()
 {
 	local status=$1
 	[ -n "$tmp_patch" ] && rm -f $tmp_patch
-	[ -n "$tmp_header" ] && rm -f $tmp_header
 	[ -n "$tmp_result" ] && rm -f $tmp_result
+	[ -n "$workdir" ] && rm -rf $workdir
 	exit $status
 }
 
-options=`getopt -o p:uU:cC:fh --long no-timestamps,diffstat,backup,sort \
-			      --long no-index \
-			      --long strip-trailing-whitespace -- "$@"`
+options=`getopt -o p:uU:cC:fz::h --long no-timestamps,diffstat,backup,sort \
+				 --long no-index \
+				 --long strip-trailing-whitespace -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -108,6 +113,10 @@ do
 		shift ;;
 	-U|-C)
 		opt_format="$1 $2"
+		shift 2 ;;
+	-z)
+		opt_fork=1
+		opt_new_name=$2
 		shift 2 ;;
 	-h)
 		usage -h ;;
@@ -144,6 +153,40 @@ QUILT_DIFF_OPTS="$QUILT_DIFF_OPTS $opt_format"
 
 patch=$(find_applied_patch "$1") || exit 1
 
+# Properly handle spaces in file names
+saved_IFS=$IFS
+IFS=$'\n'
+
+if [ -z "$opt_sort" ]
+then
+	files=( $(files_in_patch_ordered $patch) )
+else
+	files=( $(files_in_patch $patch | sort) )
+fi
+
+IFS=$saved_IFS
+
+if [ -n "$opt_fork" -a $# -ne 0 ]
+then
+	printf $"Can only refresh the topmost patch with -z currently\n" >&2
+	exit 1
+fi
+
+if [ -n "$opt_fork" ]; then
+	old_patch=$patch
+	old_patch_args=$(patch_args "$old_patch")
+	if [ -n "$opt_new_name" ]
+	then
+		patch=$opt_new_name
+	else
+		patch=$(next_filename "$patch")
+	fi
+	if [ -e "$(patch_file_name "$patch")" ]; then
+		printf $"Patch %s exists already\n" "$(print_patch $patch)" >&2
+		exit 1
+	fi
+fi
+
 if [ -z "$opt_strip_level" ]
 then
 	opt_strip_level=$(patch_strip_level $patch)
@@ -156,34 +199,37 @@ ab)
 	num_strip_level=1
 	;;
 *)
-	printf $"Cannot refresh patches with -p%s, please specify -p0 or -p1 instead\n" "$opt_strip_level\n" >&2
+	printf $"Cannot refresh patches with -p%s, please specify -p0 or -p1 instead\n" "$opt_strip_level" >&2
 	exit 1
 	;;
 esac
 
 trap "die 1" SIGTERM
 
-tmp_patch=$(gen_tempfile)
-
-if [ -z "$opt_sort" ]
-then
-	files=( $(files_in_patch_ordered $patch) )
-else
-	files=( $(files_in_patch $patch | sort) )
+if [ -n "$opt_fork" ]; then
+	workdir=$(gen_tempfile -d $PWD/quilt)
+	apply_patch_temporarily "$workdir" "$old_patch" || exit 1
 fi
+
+tmp_patch=$(gen_tempfile)
 
 for file in "${files[@]}"
 do
-	old_file=$(backup_file_name $patch $file)
-	next_patch=$(next_patch_for_file $patch $file)
-	if [ -z "$next_patch" ]
-	then
+	if [ -n "$opt_fork" ]; then
+		old_file=$workdir/$file
 		new_file=$file
 	else
-		new_file=$(backup_file_name $next_patch $file)
-		files_were_shadowed=1
+		old_file=$(backup_file_name "$patch" "$file")
+		next_patch=$(next_patch_for_file "$patch" "$file")
+		if [ -z "$next_patch" ]
+		then
+			new_file=$file
+		else
+			new_file=$(backup_file_name "$next_patch" "$file")
+			files_were_shadowed=1
+		fi
 	fi
-	if ! diff_file $file $old_file $new_file >> $tmp_patch
+	if ! diff_file "$file" "$old_file" "$new_file"
 	then
 		printf $"Diff failed, aborting\n" >&2
 		die 1
@@ -199,7 +245,7 @@ do
 	then
 		printf $"Cannot use --strip-trailing-whitespace on a patch that has shadowed files.\n" >&2
 	fi
-done
+done >> $tmp_patch
 
 if ! [ -s $tmp_patch ]
 then
@@ -227,29 +273,20 @@ patch_file=$(patch_file_name $patch)
 
 trap "" SIGINT
 
-if ! tmp_header=$(gen_tempfile)
-then
-	die 1
-fi
-
-mkdir -p $(dirname $patch_file)
-
-if ! cat_file $patch_file | patch_header > $tmp_header
-then
-	die 1
-fi
-
 tmp_result=$(gen_tempfile) || die 1
+
+prev_patch_file=$patch_file
+[ -e "$prev_patch_file" ] || prev_patch_file=/dev/null
 
 if [ -n "$opt_diffstat" ]
 then
-	diffstat="$(diffstat $QUILT_DIFFSTAT_OPTS \
-			     -p$num_strip_level $tmp_patch)" || die 1
-	awk '
+	cat_file "$prev_patch_file" | patch_header \
+	| awk '
 	    function print_diffstat(arr, i) {
-	      split(diffstat, arr, "\n")
-	      for (i=1; i in arr; i++)
-		print prefix arr[i]
+	      if (system("diffstat '"$QUILT_DIFFSTAT_OPTS \
+		      		     -p$num_strip_level \
+				     $tmp_patch | sed -e s:^:"'" prefix ":"))
+		exit 1
 	    }
 			{ prefix=""
 			  if (index($0, "#") == 1)
@@ -259,24 +296,27 @@ then
 			  next }
 	    /^#? .* files? changed(, .* insertions?\(\+\))?(, .* deletions?\(-\))?/ \
 			{ print_diffstat()
-			  diffstat = "" ; eat = ""
+			  diffstat_printed=1
+			  eat = ""
 			  next }
 			{ print eat $0
 			  eat = "" }
 	    END		{ printf "%s", eat
-	    		  if (diffstat != "") {
+	    		  if (!diffstat_printed) {
 			    print "---"
 			    print_diffstat()
 			    print prefix
 			  }
 			}
-	    ' diffstat="$diffstat" \
-	    $tmp_header > $tmp_result
+	    ' > $tmp_result
 else
-	cat $tmp_header > $tmp_result
+	cat_file "$prev_patch_file" | patch_header \
+	> $tmp_result
 fi
 
 cat $tmp_patch >> $tmp_result
+
+mkdir -p $(dirname $patch_file)
 
 if [ -e $patch_file ] && \
    diff -q $patch_file $tmp_result > /dev/null
@@ -286,8 +326,30 @@ elif ( [ -z "$QUILT_BACKUP" -o ! -e $patch_file ] || \
        mv $patch_file $patch_file~ ) && \
      cat_to_new_file $patch_file < $tmp_result
 then
+	if [ -n "$opt_fork" ]
+	then
+		if ! insert_in_series "$patch" "$old_patch_args"
+		then
+			printf $"Failed to insert patch %s into file series\n" \
+			       "$(print_patch $patch)" >&2
+			rm -f "$patch_file"
+			exit 1
+		fi
+		if ! rm -rf "$QUILT_PC/$patch" || \
+		   ! mv "$workdir" "$QUILT_PC/$patch" || \
+		   ! echo "$patch" >> $QUILT_PC/applied-patches
+		then
+			printf $"Failed to create patch %s\n" \
+			       "$(print_patch $patch)" >&2
+			exit 1
+		fi
+		printf $"Fork of patch %s created as %s\n" \
+			"$(print_patch $old_patch)" \
+			"$(print_patch $patch)"
+	else
+		printf $"Refreshed patch %s\n" "$(print_patch $patch)"
+	fi
 	touch $QUILT_PC/$patch/.timestamp
-	printf $"Refreshed patch %s\n" "$(print_patch $patch)"
 else
 	die 1
 fi
diff --git a/usr/share/quilt/scripts/patchfns b/usr/share/quilt/scripts/patchfns
--- a/usr/share/quilt/scripts/patchfns
+++ b/usr/share/quilt/scripts/patchfns
@@ -1,5 +1,3 @@
-#! /bin/bash
-
 # This file contains the common functions used in all quilt script
 # It is meant to be sourced by bash scripts.
 
@@ -20,7 +18,6 @@ export LANG=POSIX
 export QUILT_PATCHES QUILT_PC SUBDIR SERIES DB
 DB_VERSION=2
 
-: ${QUILT_PATCHES:=patches}
 : ${QUILT_PC:=.pc}
 
 # Support compatibility layer
@@ -44,32 +41,38 @@ if [ -n "$QUILT_COMMAND" ]; then
 	unset args
 fi
 
+. $QUILT_DIR/scripts/utilfns
+
 # ========================================================
 
-#declare -a exit_handlers
-#
-#add_exit_handler() {
-#	exit_handlers[${#exit_handlers[@]}]=$1
-#}
-#
-#remove_exit_handler() {
-#	declare -a handlers
-#	local h
-#	for h in "${exit_handlers[@]}"; do
-#		[ "$h" = "$1" ] && continue
-#		handlers[${#handlers[@]}]=$h
-#	done
-#	exit_handlers=( "${handlers[@]}" )
-#}
-#
-#run_exit_handlers() {
-#	local h
-#	for h in "${exit_handlers[@]}"; do
-#		eval $h
-#	done
-#}
-#
-#trap run_exit_handlers EXIT
+declare -a exit_handlers
+
+add_exit_handler() {
+	exit_handlers[${#exit_handlers[@]}]=$1
+}
+
+remove_exit_handler()
+{
+	declare -a handlers
+	local h
+	for h in "${exit_handlers[@]}"
+	do
+		[ "$h" = "$1" ] && continue
+		handlers[${#handlers[@]}]=$h
+	done
+	exit_handlers=( "${handlers[@]}" )
+}
+
+run_exit_handlers()
+{
+	local h
+	for h in "${exit_handlers[@]}"
+	do
+		eval $h
+	done
+}
+
+trap run_exit_handlers EXIT
 
 # ========================================================
 
@@ -83,42 +86,6 @@ quote_bre()
 quote_re()
 {
 	echo "$1" | sed -e 's:\([][?{(|)}^$/.+*\\]\):\\\1:g'
-}
-
-basename()
-{
-	local path=$1
-	while [ "${path:(-1)}" = "/" ]
-	do
-		path=${path%/}
-	done
-	echo "${path##*/}"
-}
-
-dirname()
-{
-	local path=$1
-	while [ "${path:(-1)}" = "/" ]
-	do
-		path=${path%/}
-	done
-	local basename="${path##*/}"
-	path="${path:0:${#path}-${#basename}}"
-	while [ "${path:(-1)}" = "/" ]
-	do
-		path=${path%/}
-	done
-	if [ -n "$path" ]
-	then
-		echo "$path"
-	else
-		if [ ${1:0:1} = "/" ]
-		then
-			echo "/"
-		else
-			echo "."
-		fi
-	fi
 }
 
 patch_file_name()
@@ -136,10 +103,13 @@ patch_args()
 		awk '
 			{sub(/(^|[ \t]+)#.*/, "") }
 		$1 == "'"$patch"'" \
-			{ if (NF >= 2)
-				for (i=2; i <= NF; i++)
-					print $i
-			  else
+			{ p_printed=0
+			  for (i=2; i<=NF; i++) {
+				print $i
+				if ($i ~ /^-p/)
+					p_printed=1
+			  }
+			  if (!p_printed)
 				print "-p1" ;
 			  exit
 			}
@@ -153,9 +123,6 @@ patch_strip_level()
 	for i in $(patch_args $patch)
 	do
 		case $i in
-		-p)
-			echo $2
-			return ;;
 		-p*)
 			echo ${i:2}
 			return ;;
@@ -164,6 +131,7 @@ patch_strip_level()
 	echo "1"
 }
 
+# Also remove -R if present.
 change_db_strip_level()
 {
 	local level=$1 patch=$2
@@ -179,14 +147,35 @@ change_db_strip_level()
 	then
 		local tmpfile=$(gen_tempfile)
 		awk '
+		function remove_arg(nr, j) {
+			for (j=nr; j<NF; j++)
+				$j=$(j+1)
+			NF--
+		}
+		function insert_arg(nr, value, j) {
+			for (j=NF; j>=nr; j--)
+				$(j+1)=$j
+			$nr=value
+		}
+
 		/^'"$(quote_re $patch)"'([ \t]|$)/ \
-			{ for(i=2; i<=NF; i++)
+			{ p_printed=0
+			  for (i=2; i<=NF && $i !~ /^#/; i++) {
 				if ($i ~ /^-p/) {
-					$i="'"$level"'"
-					break
+					if ("'"$level"'" == "")
+						remove_arg(i--)
+					else
+						$i="'"$level"'"
+					p_printed=1
+					continue
 				}
-			  if (i > NF && "'"$level"'" != "")
-				 $i="'"$level"'"
+				if ($i == "-R") {
+					remove_arg(i--)
+					continue
+				}
+			  }
+			  if (!p_printed && "'"$level"'" != "")
+			  	insert_arg(2, "'"$level"'")
 			}
 			{ print }
 		' $SERIES > $tmpfile
@@ -216,7 +205,14 @@ patch_in_series()
 insert_in_series()
 {
 	local patch=$1 patch_args=$2
-	local next=$(patch_after "$(top_patch)") tmpfile
+	local before tmpfile
+
+	if [ -e "$SERIES" -a ! -f "$SERIES" ]; then
+		printf $"%s is not a regular file\n" "$SERIES" >&2
+		return 1
+	fi
+
+	before=${3-$(patch_after "$(top_patch)")}
 
 	if [ -n "$patch_args" ]
 	then
@@ -225,13 +221,13 @@ insert_in_series()
 
 	tmpfile=$(gen_tempfile) || return 1
 	mkdir -p $(dirname $SERIES)
-	if [ -n "$next" ]
+	if [ -n "$before" ]
 	then
 		awk '
-		/^'"$(quote_re $next)"'([ \t]|$)/ \
+		/^'"$(quote_re $before)"'([ \t]|$)/ \
 				{ print "'"$patch$patch_args"'" }
 				{ print }
-		' $SERIES > $tmpfile
+		' "$SERIES" > $tmpfile
 		status=$?
 		if [ $status -ne 0 ]
 		then
@@ -239,13 +235,13 @@ insert_in_series()
 			return 1
 		fi
 	else
-		if [ -e $SERIES ]
+		if [ -e "$SERIES" ]
 		then
-			cat $SERIES > $tmpfile
+			cat "$SERIES" > $tmpfile
 		fi
 		echo "$patch$patch_args" >> $tmpfile
 	fi
-	cat $tmpfile > $SERIES
+	cat $tmpfile > "$SERIES"
 	rm -f $tmpfile
 }
 
@@ -324,9 +320,12 @@ cat_series()
 {
 	if [ -e $SERIES ]
 	then
-		sed -e '/^$/d' -e '/^#/d' -e 's/^[ '$'\t'']*//' \
-		    -e 's/[ '$'\t''].*//' $SERIES
+		sed -e '/^#/d' -e 's/^[ '$'\t'']*//' \
+		    -e 's/[ '$'\t''].*//' -e '/^$/d' $SERIES
 	else
+		if [ "$opt_verbose" ]; then
+			echo "series file not found: $SERIES" >&2
+		fi
 		return 1
 	fi
 }
@@ -458,8 +457,30 @@ find_first_patch()
 	local patch=$(cat_series | head -n 1)
 	if [ -z "$patch" ]
 	then
-		printf $"No patches in series\n" >&2
+		if [ -e "$SERIES" ]
+		then
+			printf $"No patches in series\n" >&2
+		else
+			printf $"No series file found\n" >&2
+		fi
 		return 1
+	fi
+
+	echo "$patch"
+}
+
+find_last_patch()
+{
+	local patch=$(cat_series | tail -n 1)
+	if [ -z "$patch" ]
+	then
+		if [ -e "$SERIES" ]
+		then
+			printf $"No patches in series\n" >&2
+		else
+			printf $"No series file found\n" >&2
+		fi
+		return 2
 	fi
 
 	echo "$patch"
@@ -482,9 +503,15 @@ find_patch()
 	local name="$1"
 	if [ -e "$SERIES" ]
 	then
+		if ! [ -f "$SERIES" ]
+		then
+			printf $"%s is not a regular file\n" "$SERIES" >&2
+			return 1
+		fi
+
 		local patch=${1#$SUBDIR_DOWN$QUILT_PATCHES/}
 		local bre=$(quote_bre "$patch")
-		set -- $(sed -e "/^$bre\(\|\.patch\|\.diff\?\)\(\|\.gz\|\.bz2\)\([ "$'\t'"]\|$\)/!d" \
+		set -- $(sed -e "/^$bre\(\|\.patch\|\.diff\?\)\(\|\.gz\|\.bz2\|\.xz\|\.lzma\)\([ "$'\t'"]\|$\)/!d" \
 			       -e 's/[ '$'\t''].*//' $SERIES)
 		if [ $# -eq 1 ]
 		then
@@ -558,7 +585,7 @@ find_unapplied_patch()
 	        then
 			printf $"Patch %s is currently applied\n" \
 				"$(print_patch $patch)" >&2
-               		return 1
+               		return 2
 	        fi
 		echo "$patch"
 	else
@@ -568,13 +595,13 @@ find_unapplied_patch()
 		then
 			patch_after "$start"
 		else
-			find_first_patch || return 1
+			find_first_patch || return 2
 		fi
 		if [ $? -ne 0 ]
 		then
 			printf $"File series fully applied, ends at patch %s\n" \
 				"$(print_patch $start)" >&2
-			return 1
+			return 2
 		fi
 	fi
 }
@@ -583,10 +610,21 @@ find_patch_file()
 {
 	local name="$1"
 
-	if [ -r "$name" ]
+	if [ ${name:0:1} = / ]
 	then
-		echo "$name"
-		return
+		# Patch has absolute path
+		if [ -r "$name" ]
+		then
+			echo "$name"
+			return
+		fi
+	else
+		# Patch has a relative path
+		if [ -r "$SUBDIR$name" ]
+		then
+			echo "$SUBDIR$name"
+			return
+		fi
 	fi
 
 	local patch
@@ -614,11 +652,9 @@ files_in_patch()
 
 	if [ -d "$path" ]
 	then
-		local files
-		files=( $(find "$path" -type f \
-			       -a ! -path "$path/.timestamp") ) \
-		|| return 1
-		printf "%s\n" "${files[@]#$path/}"
+		find "$path" -type f \
+			       -a ! -path "$path/.timestamp" |
+		sed -e "s:$path/::"
 	fi
 }
 
@@ -711,8 +747,9 @@ diff_file()
 					-r "$new_file")
 	fi
 
-	diff $QUILT_DIFF_OPTS $old_file $new_file \
+	diff $QUILT_DIFF_OPTS \
 	     --label "$old_hdr$old_date" --label "$new_hdr$new_date" \
+	     "$old_file" "$new_file" \
 	| if read line
 	then
 		if [ -z "$QUILT_NO_DIFF_INDEX" ]
@@ -738,6 +775,10 @@ cat_file()
 				gzip -cd "$filename" ;;
 			*.bz2)
 				bzip2 -cd "$filename" ;;
+			*.xz)
+				xz -cd "$filename" ;;
+			*.lzma)
+				lzma -cd "$filename" ;;
 			*)
 				cat "$filename" ;;
 			esac
@@ -756,6 +797,10 @@ cat_to_new_file()
 		gzip -c ;;
 	*.bz2)
 		bzip2 -c ;;
+	*.xz)
+		xz -c ;;
+	*.lzma)
+		lzma -c ;;
 	*)
 		cat ;;
 	esac \
@@ -805,17 +850,6 @@ in_array()
 	return 1
 }
 
-gen_tempfile()
-{
-	local name
-	if [ "$1" = -d ]
-	then
-		mktemp -d ${2:-${TMPDIR:-/tmp}/${0// /_}}.XXXXXX
-	else
-		mktemp ${1:-${TMPDIR:-/tmp}/${0// /_}}.XXXXXX
-	fi
-}
-
 first_modified_by()
 {
 	local file=$1 patch
@@ -838,11 +872,68 @@ first_modified_by()
 	return 1
 }
 
+apply_patch_temporarily()
+{
+	local workdir=$1 patch=$2 patch_file patch_args
+
+	patch_file=$(patch_file_name "$patch")
+	patch_args=$(patch_args "$patch")
+
+	shift 2
+
+	local prefix=$QUILT_PC/$patch/
+	[ ${prefix:0:1} == / ] || prefix=$PWD/$prefix
+	if ! ( cd $workdir && \
+	       $QUILT_DIR/scripts/backup-files -B $prefix -r -k -s ${@:--} )
+	then
+		printf $"Failed to copy files to temporary directory\n" >&2
+		return 1
+	fi
+
+	if [ -s $patch_file ]
+	then
+		if ! cat_file $patch_file \
+		     | patch -d $workdir $QUILT_PATCH_OPTS $patch_args \
+		     	     --no-backup-if-mismatch -Ef \
+			     >/dev/null 2>/dev/null
+		then
+			# Generating a relative diff for a subset of files in
+			# the patch will fail. Also, if a patch was force
+			# applied, we know that it won't apply cleanly. In
+			# all other cases, print a warning.
+
+			if [ ! -e $QUILT_PC/$patch~refresh -a $# -eq 0 ]
+			then
+				printf $"Failed to patch temporary files\n" >&2
+				return 1
+			fi
+		fi
+	fi
+}
+
+next_filename()
+{
+	local patch=$1 base num
+        base=$(echo "$patch" \
+               | sed -r -e 's:(\.gz|\.bz2|\.xz|\.lzma)$::' -e 's:(\.diff?|\.patch)$::')
+        num=$(echo "$base" | sed -nre 's:.*-([0-9]+)$:\1:'p)
+        [ -n "$num" ] || num=1
+        echo "${base%-$num}-$((num+1))${patch#$base}"
+}
+
 create_db() {
 	if ! [ -e $QUILT_PC ]
 	then
 		mkdir -p $QUILT_PC
 		echo $DB_VERSION > $QUILT_PC/.version
+	fi
+	if ! [ -e $QUILT_PC/.quilt_patches ]
+	then
+		echo "$QUILT_PATCHES" > $QUILT_PC/.quilt_patches
+	fi
+	if ! [ -e $QUILT_PC/.quilt_series ]
+	then
+		echo "$QUILT_SERIES" > $QUILT_PC/.quilt_series
 	fi
 }
 
@@ -870,7 +961,7 @@ print_patch() {
 
 setup_colors()
 {
-	local C=diff_hdr=32:diff_add=36:diff_mod=35:diff_rem=35:diff_hunk=33:diff_ctx=35:diff_cctx=33:patch_offs=33:patch_fuzz=35:patch_fail=31:patch_applied=32:clear=00
+	local C=diff_hdr=32:diff_add=36:diff_mod=35:diff_rem=35:diff_hunk=33:diff_ctx=35:diff_cctx=33:patch_offs=33:patch_fuzz=35:patch_fail=31:patch_applied=32:series_app=32:series_top=33:series_una=00:clear=00
 	[ -n "$QUILT_COLORS" ] && C="$C:$QUILT_COLORS"
 
 	C=${C//=/=\'$'\e'[}
@@ -884,6 +975,52 @@ quilt_command()
 	shift
 
 	QUILT_COMMAND="" bash $BASH_OPTS -c "${SUBDIR:+cd $SUBDIR;} . $QUILT_DIR/$command" "quilt $command" "$@"
+}
+
+declare pager_fifo pager_fifo_dir pager_pid
+
+wait_for_pager()
+{
+	exec >&-
+	wait $pager_pid
+	rm $pager_fifo 2>/dev/null
+	rmdir $pager_fifo_dir 2>/dev/null
+}
+
+wait_for_pager_signal()
+{
+	remove_exit_handler wait_for_pager
+	wait_for_pager
+	trap - INT HUP TERM QUIT
+}
+
+# Spawn pager process and redirect the rest of our output to it
+setup_pager()
+{
+	test -t 1 || return 0
+
+	# QUILT_PAGER = QUILT_PAGER | GIT_PAGER | PAGER | less
+	# NOTE: QUILT_PAGER='' is significant
+	QUILT_PAGER=${QUILT_PAGER-${GIT_PAGER-${PAGER-less}}}
+
+	[ -z "$QUILT_PAGER" -o "$QUILT_PAGER" = "cat" ]  && return 0
+
+	export LESS="${LESS:-FRSX}"
+
+	# NOTE: with "exec > >($pager)" there is no way to get the pid of the
+	# pager so we can't wait for it to complete.  Otherwise we wouldn't
+	# need temporary files here.  Alternatively, in recent versions of
+	# bash, a coprocess could be used instead.
+
+	pager_fifo_dir="$(gen_tempfile -d)"
+	pager_fifo="$pager_fifo_dir/0"
+	mkfifo -m 600 "$pager_fifo"
+	$QUILT_PAGER < "$pager_fifo" &
+	pager_pid=$!
+	exec > "$pager_fifo"
+
+	trap wait_for_pager_signal INT HUP TERM QUIT
+	add_exit_handler wait_for_pager
 }
 
 #
@@ -900,14 +1037,14 @@ quilt_command()
 # drivers/net/.
 
 unset SUBDIR SUBDIR_DOWN
-if ! [ -d "$QUILT_PATCHES" ]
+if ! [ -d "$QUILT_PC" -o -d "${QUILT_PATCHES:-patches}" ]
 then
     basedir=$PWD
     while [ -n "$basedir" ]
     do
 	basedir=${basedir%/*}
 	down=$down../
-	if [ -d "$basedir/$QUILT_PATCHES" ]
+	if [ -d "$basedir/$QUILT_PC" -o -d "$basedir/${QUILT_PATCHES:-patches}" ]
 	then
 	    SUBDIR="${PWD#$basedir/}/"
 	    SUBDIR_DOWN=$down
@@ -922,17 +1059,30 @@ then
     unset basedir down
 fi
 
-if [ -n "$QUILT_SERIES" ]
+if [ -r $QUILT_PC/.quilt_patches ]
+then
+	: ${QUILT_PATCHES:=$(< $QUILT_PC/.quilt_patches)}
+else
+	: ${QUILT_PATCHES:=patches}
+fi
+if [ -r $QUILT_PC/.quilt_series ]
+then
+	: ${QUILT_SERIES:=$(< $QUILT_PC/.quilt_series)}
+else
+	: ${QUILT_SERIES:=series}
+fi
+
+if [ "${QUILT_SERIES:0:1}" = / ]
 then
 	SERIES=$QUILT_SERIES
-elif [ -e $QUILT_PC/series ]
+elif [ -f $QUILT_PC/$QUILT_SERIES ]
 then
-	SERIES=$QUILT_PC/series
-elif [ -e series ]
+	SERIES=$QUILT_PC/$QUILT_SERIES
+elif [ -f $QUILT_SERIES ]
 then
-	SERIES=series
+	SERIES=$QUILT_SERIES
 else
-	SERIES=$QUILT_PATCHES/series
+	SERIES=$QUILT_PATCHES/$QUILT_SERIES
 fi
 
 DB="$QUILT_PC/applied-patches"
